In [1]:
# Imports and Setup
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('nhanes_all.csv')

In [3]:
df.head()

,SEQN,LBXVIDMS,LBXSATSI,LBXSAL,LBXSAPSI,LBXSASSI,LBXSBU,LBXSCK,LBDSCRSI,LBXSGTSI,...,BPXOPLS2,BPXOPLS3,DSQTFA,DSQTVB12,DSQTVD,DSQTCALC,DSQTPHOS,DSQTMAGN,DSQTIRON,DSQTPOTA
0,130378.0,58.9,39.0,4.3,91.0,25.0,11.0,172.0,70.72,41.0,...,79.0,82.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,130379.0,60.5,17.0,3.9,64.0,20.0,24.0,98.0,69.84,31.0,...,71.0,73.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,130380.0,39.4,13.0,3.7,78.0,15.0,10.0,38.0,56.58,44.0,...,83.0,77.0,NaN,NaN,NaN,NaN,NaN,NaN,0.013,1.0
3,130381.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,320.0,1.92,18.0,112.0,NaN,NaN,8.000,NaN
4,130382.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,100.0,1.20,10.0,NaN,NaN,NaN,NaN,NaN

In [4]:
df.shape

(11933, 206)

In [5]:
df.describe()

,SEQN,LBXVIDMS,LBXSATSI,LBXSAL,LBXSAPSI,LBXSASSI,LBXSBU,LBXSCK,LBDSCRSI,LBXSGTSI,...,BPXOPLS2,BPXOPLS3,DSQTFA,DSQTVB12,DSQTVD,DSQTCALC,DSQTPHOS,DSQTMAGN,DSQTIRON,DSQTPOTA
count,11933.000000,7307.000000,6321.000000,6366.000000,6327.000000,6308.000000,6326.000000,6321.000000,6326.000000,6327.000000,...,7505.000000,7480.000000,2183.000000,2411.000000,3016.000000,2426.000000,834.000000,1613.000000,1051.000000,960.000000
mean,136344.000000,77.458826,21.065338,4.099246,94.272641,22.301046,14.659817,148.650372,77.157959,28.081871,...,73.087009,73.685027,508.511681,251.395790,45.897006,308.930627,34.203837,130.610105,18.698257,97.254479
std,3444.904716,36.218293,16.056092,0.355161,51.711316,14.291143,5.754035,313.309165,34.078007,44.083023,...,12.775995,12.893922,473.879537,755.158174,54.927905,361.979520,51.396107,156.200522,22.635952,183.628323
min,130378.000000,7.970000,3.000000,2.200000,20.000000,6.000000,4.000000,10.000000,29.170000,2.000000,...,32.000000,31.000000,1.000000,0.020000,0.040000,0.500000,0.200000,0.200000,0.003000,0.200000
25%,133361.000000,53.000000,12.000000,3.900000,68.000000,16.000000,11.000000,69.000000,61.880000,13.000000,...,64.000000,65.000000,200.000000,3.000000,14.580000,70.000000,18.700000,41.700000,5.400000,40.000000
50%,136344.000000,72.000000,17.000000,4.100000,83.000000,20.000000,14.000000,100.000000,73.370000,18.000000,...,72.000000,73.000000,408.000000,8.900000,25.000000,200.000000,20.000000,75.000000,11.000000,80.000000
75%,139327.000000,95.650000,25.000000,4.300000,103.000000,24.000000,17.000000,157.000000,86.630000,29.000000,...,81.000000,82.000000,667.000000,58.000000,50.925000,400.000000,21.175000,140.000000,18.000000,80.000000
max,142310.000000,424.000000,350.000000,5.500000,731.000000,518.000000,74.000000,16837.000000,1341.030000,1541.000000,...,141.000000,154.000000,9032.000000,9333.330000,1262.080000,3383.300000,583.300000,1691.700000,150.000000,3120.000000

In [6]:
len(df['SEQN'].unique())

11933

In [7]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11933 entries, 0 to 11932
Data columns (total 206 columns):
 #    Column    Dtype
---   ------    -----
 0    SEQN      float64
 1    LBXVIDMS  float64
 2    LBXSATSI  float64
 3    LBXSAL    float64
 4    LBXSAPSI  float64
 5    LBXSASSI  float64
 6    LBXSBU    float64
 7    LBXSCK    float64
 8    LBDSCRSI  float64
 9    LBXSGTSI  float64
 10   LBXMAGN   float64
 11   LBXSPH    float64
 12   LBXSKSI   float64
 13   LBXSNASI  float64
 14   LBXSCA    float64
 15   LBXSTP    float64
 16   LBXSUA    float64
 17   LBXHSCRP  float64
 18   LBXGH     float64
 19   LBDFOT    float64
 20   LBXFER    float64
 21   LBXWBCSI  float64
 22   LBXHGB    float64
 23   LBXHCT    float64
 24   LBXTC     float64
 25   LBXTLG    float64
 26   LBDLDLN   float64
 27   LBDHDD    float64
 28   RHQ131    float64
 29   RHD167    float64
 30   RXQ515    float64
 31   RXQ520    float64
 32   RXQ033    float64
 33   RXQ050    float64
 34   OCD150    float64
 35   OCQ180    float64
 36   OCQ210    float64
 37   OCQ215    float64
 38   MCQ035    float64
 39   AGQ030    float64
 40   MCQ053    float64
 41   MCQ195    float64
 42   MCQ500    float64
 43   OSQ230    float64
 44   KIQ022    float64
 45   KIQ005    float64
 46   KIQ481    float64
 47   HUQ010    float64
 48   HUQ030    float64
 49   HUQ042    float64
 50   HUQ090    float64
 51   HIQ011    float64
 52   DIQ010    float64
 53   DIQ180    float64
 54   DIQ070    float64
 55   BAQ110    float64
 56   BAQ121    float64
 57   BAQ125    float64
 58   BAQ132    float64
 59   BAQ140    float64
 60   BAQ150    float64
 61   BAQ160    float64
 62   BAQ201    float64
 63   BAXTC11   float64
 64   BAXTC12   float64
 65   BAXTC21   float64
 66   BAXTC22   float64
 67   BAXTC31   float64
 68   BAXTC32   float64
 69   BAXTC41   float64
 70   BAXTC42   float64
 71   BAXTC51   float64
 72   BAXTC52   float64
 73   DR2TKCAL  float64
 74   DR2TPROT  float64
 75   DR2TCARB  float64
 76   DR2TSUGR  float64
 77   DR2TFIBE  float64
 78   DR2TTFAT  float64
 79   DR2TSFAT  float64
 80   DR2TMFAT  float64
 81   DR2TPFAT  float64
 82   DR2TCHOL  float64
 83   DR2TSODI  float64
 84   DR2TCAFF  float64
 85   DR2_300   float64
 86   DR2_320Z  float64
 87   DBD100    float64
 88   DRQSPREP  float64
 89   DRQSDIET  float64
 90   DR1TKCAL  float64
 91   DR1TPROT  float64
 92   DR1TCARB  float64
 93   DR1TSUGR  float64
 94   DR1TFIBE  float64
 95   DR1TTFAT  float64
 96   DR1TSFAT  float64
 97   DR1TMFAT  float64
 98   DR1TPFAT  float64
 99   DR1TCHOL  float64
 100  DR1TSODI  float64
 101  DR1TCAFF  float64
 102  DR1_300   float64
 103  DR1_320Z  float64
 104  DRD340    float64
 105  DRD360    float64
 106  FNQ410    float64
 107  FNQ430    float64
 108  FNQ440    float64
 109  FNQ450    float64
 110  FNQ460    float64
 111  FNQ490    float64
 112  FNQ510    float64
 113  FNQ520    float64
 114  FNQ530    float64
 115  FNQ540    float64
 116  RIAGENDR  float64
 117  RIDAGEYR  float64
 118  RIDRETH3  float64
 119  RIDEXMON  float64
 120  DMDMARTZ  float64
 121  RIDEXPRG  float64
 122  INDFMPIR  float64
 123  BAQ321A   float64
 124  BAQ321B   float64
 125  BAQ321C   float64
 126  BAQ321D   float64
 127  BAQ341    float64
 128  BAQ391A   float64
 129  BAQ391B   float64
 130  BAQ401    float64
 131  BAQ421    float64
 132  BAQ530    float64
 133  BAQ550    float64
 134  BAQ560    float64
 135  PHQ050    float64
 136  DPQ010    float64
 137  DPQ020    float64
 138  DPQ030    float64
 139  DPQ040    float64
 140  DPQ050    float64
 141  DPQ060    float64
 142  DPQ070    float64
 143  DPQ090    float64
 144  BPQ150    float64
 145  BPQ101D   float64
 146  DR1_040Z  float64
 147  DR2_040Z  float64
 148  SMQ681    float64
 149  SMQ846    float64
 150  SMQ851    float64
 151  FSD032A   float64
 152  FSD032B   float64
 153  FSD032C   float64
 154  FSD041    float64
 155  FSD052    float64
 156  FSD071    float64
 157  FSD092    float64
 158  FSD102    float64
 159  FSDAD     float64
 160  SMD470    float64
 161  SMQ040    float64
 162  SMD641    float64
 163  SMD650    float64
 164  SLD012    float64
 165  SLD013    float64
 166  PAD790Q   float64
 167  PAD790U   object
 168  PAD800    float64
 169  PAD810Q   float64
 170  PAD810U   object
 171  PAD820    float64
 172  PAD680    float64
 173  OHQ845    float64
 174  DSD010    float64
 175  DSD010AN  float64
 176  DEQ034A   float64
 177  DEQ034C   float64
 178  DEQ034D   float64
 179  AUQ054    float64
 180  AUQ101    float64
 181  ALQ111    float64
 182  ALQ121    float64
 183  ALQ130    float64
 184  ALQ142    float64
 185  ALQ280    float64
 186  BMXWT     float64
 187  BMXHT     float64
 188  BMXBMI    float64
 189  BPXOSY1   float64
 190  BPXODI1   float64
 191  BPXOSY2   float64
 192  BPXODI2   float64
 193  BPXOSY3   float64
 194  BPXODI3   float64
 195  BPXOPLS1  float64
 196  BPXOPLS2  float64
 197  BPXOPLS3  float64
 198  DSQTFA    float64
 199  DSQTVB12  float64
 200  DSQTVD    float64
 201  DSQTCALC  float64
 202  DSQTPHOS  float64
 203  DSQTMAGN  float64
 204  DSQTIRON  float64
 205  DSQTPOTA  float64
dtypes: float64(204), object(2)
memory usage: 18.8+ MB

In [8]:
pd.set_option('display.max_rows', None)
display(df.isnull().sum())

SEQN            0
LBXVIDMS     4626
LBXSATSI     5612
LBXSAL       5567
LBXSAPSI     5606
LBXSASSI     5625
LBXSBU       5607
LBXSCK       5612
LBDSCRSI     5607
LBXSGTSI     5606
LBXMAGN      5609
LBXSPH       5611
LBXSKSI      5652
LBXSNASI     5567
LBXSCA       5571
LBXSTP       5569
LBXSUA       5604
LBXHSCRP     4651
LBXGH        5218
LBDFOT       4585
LBXFER       9983
LBXWBCSI     4340
LBXHGB       4340
LBXHCT       4340
LBXTC        5043
LBXTLG       8416
LBDLDLN      8420
LBDHDD       5043
RHQ131      10390
RHD167      10886
RXQ515       9885
RXQ520       8271
RXQ033         40
RXQ050       5687
OCD150       3450
OCQ180       7841
OCQ210      10494
OCQ215       7431
MCQ035      10024
AGQ030        201
MCQ053        200
MCQ195       9902
MCQ500      10356
OSQ230       6246
KIQ022       4139
KIQ005       6730
KIQ481       6752
HUQ010          7
HUQ030         10
HUQ042       1237
HUQ090        791
HIQ011         62
DIQ010        197
DIQ180       3896
DIQ070       9659
BAQ110       7570
BAQ121       7629
BAQ125       7656
BAQ132       7911
BAQ140       7912
BAQ150       7961
BAQ160       8315
BAQ201       8646
BAXTC11      7983
BAXTC12     11885
BAXTC21      7991
BAXTC22     11839
BAXTC31      8051
BAXTC32     11854
BAXTC41      8083
BAXTC42     10614
BAXTC51      9338
BAXTC52     10710
DR2TKCAL     6103
DR2TPROT     6103
DR2TCARB     6103
DR2TSUGR     6103
DR2TFIBE     6103
DR2TTFAT     6103
DR2TSFAT     6103
DR2TMFAT     6103
DR2TPFAT     6103
DR2TCHOL     6103
DR2TSODI     6103
DR2TCAFF     6103
DR2_300      6046
DR2_320Z     6054
DBD100       7201
DRQSPREP     5223
DRQSDIET     5175
DR1TKCAL     5239
DR1TPROT     5239
DR1TCARB     5239
DR1TSUGR     5239
DR1TFIBE     5239
DR1TTFAT     5239
DR1TSFAT     5239
DR1TMFAT     5239
DR1TPFAT     5239
DR1TCHOL     5239
DR1TSODI     5239
DR1TCAFF     5239
DR1_300      5197
DR1_320Z     5179
DRD340       5293
DRD360       5291
FNQ410       3797
FNQ430       3816
FNQ440       3795
FNQ450       3793
FNQ460       3796
FNQ490       3795
FNQ510       3809
FNQ520       5328
FNQ530       3818
FNQ540       6932
RIAGENDR        0
RIDAGEYR        0
RIDRETH3        0
RIDEXMON     3073
DMDMARTZ     4150
RIDEXPRG    10827
INDFMPIR     2041
BAQ321A      5884
BAQ321B      5880
BAQ321C      5880
BAQ321D      5880
BAQ341       9811
BAQ391A      9813
BAQ391B      9813
BAQ401       9795
BAQ421       9794
BAQ530       5903
BAQ550       9130
BAQ560      10214
PHQ050       3297
DPQ010       6435
DPQ020       6425
DPQ030       6424
DPQ040       6427
DPQ050       6423
DPQ060       6428
DPQ070       6428
DPQ090       6432
BPQ150       8968
BPQ101D      3468
DR1_040Z     5211
DR2_040Z     6079
SMQ681       5668
SMQ846       5670
SMQ851       5674
FSD032A      1357
FSD032B      1362
FSD032C      1358
FSD041       8296
FSD052      10406
FSD071       8292
FSD092      10122
FSD102      11577
FSDAD        1352
SMD470       9330
SMQ040       8690
SMD641      11665
SMD650      10853
SLD012       3615
SLD013       3631
PAD790Q      3847
PAD790U      5543
PAD800       5562
PAD810Q      3834
PAD810U      8247
PAD820       8260
PAD680       3868
OHQ845        210
DSD010       5202
DSD010AN     5213
DEQ034A      7635
DEQ034C      7663
DEQ034D      7662
AUQ054        196
AUQ101       4150
ALQ111       6457
ALQ121       7016
ALQ130       7898
ALQ142       7871
ALQ280       9581
BMXWT        3179
BMXHT        3434
BMXBMI       3462
BPXOSY1      4416
BPXODI1      4416
BPXOSY2      4428
BPXODI2      4428
BPXOSY3      4453
BPXODI3      4453
BPXOPLS1     4416
BPXOPLS2     4428
BPXOPLS3     4453
DSQTFA       9750
DSQTVB12     9522
DSQTVD       8917
DSQTCALC     9507
DSQTPHOS    11099
DSQTMAGN    10320
DSQTIRON    10882
DSQTPOTA    10973
dtype: int64

# Data Cleaning

In [9]:
df_copy = df.copy()

In [10]:
# Filter respondents that are under 18 and over 80, and that are pregnant

# View the number of participants that are younger than 18 years old
num_under_18 = df_copy[df_copy['RIDAGEYR'] < 18].shape[0]
print(f"Number of participants younger than 18 years old: {num_under_18}")

# View the number of participants that are older than 80 years old
num_over_80 = df_copy[df_copy['RIDAGEYR'] > 80].shape[0]
print(f"Number of participants older than 80 years old: {num_over_80}")

# View the number of paritcipants that are pregnant at the time of the exam
num_pregnant = df_copy[df_copy['RIDEXPRG'] == 1].shape[0]
print(f"Number of participants that were pregnant at the time of the exam: {num_pregnant}")

# View the number of participants that were pregnant and younger than 18 years old
num_pregnant_under_18 = df_copy[(df_copy['RIDEXPRG'] == 1) & (df_copy['RIDAGEYR'] < 18)].shape[0]
print(f"Number of participants that were pregnant and younger than 18 years old: {num_pregnant_under_18}")

# View the number of participants that were pregnant and older than 80 years old
num_pregnant_over_80 = df_copy[(df_copy['RIDEXPRG'] == 1) & (df_copy['RIDAGEYR'] > 80)].shape[0]
print(f"Number of participants that were pregnant and older than 80 years old: {num_pregnant_over_80}")

Number of participants younger than 18 years old: 3780
Number of participants older than 80 years old: 0
Number of participants that were pregnant at the time of the exam: 41
Number of participants that were pregnant and younger than 18 years old: 0
Number of participants that were pregnant and older than 80 years old: 0

In [11]:
df_copy = df_copy[
    (df_copy['RIDAGEYR'] > 17) &
    (df_copy['RIDAGEYR'] < 80) &
    (df_copy['RIDEXPRG'] != 1)]

df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7587 entries, 0 to 11931
Columns: 206 entries, SEQN to DSQTPOTA
dtypes: float64(204), object(2)
memory usage: 12.0+ MB

After reviewing the features in more detail the following features should be removed:

*   PHQ050 - This question is exclusively about the fasting period for lab tests not in general
*   FSD032A, FSD032B, FSD032C, FSD041, FSD052, FSD071, FSD092, FSD102 - These are all components of FSDAD. Remove to reduce redundancy and keep only FSDAD.
* BMXWT and BMXHT are used to calculate BMXBMI. Remove to reduce multicolinearity
* ALQ111 - having over 1 drink in a person's entire life does not provide enough detail about overall health
* RXQ033 - it is implied that this variable is 'yes' if they respond with 1 or more in RXQ050. Remove to reduce redundancy.
* OCQ210 - Redundant with OCQ180
(number of hours worked per week)
* HUQ042 - does not provide valuable health information
* DIQ180 - only relevant for blood sugar not all blood tests
* BAQ341 - redundant with BAQ321A-D
* BAQ421 - redundant with BAQ401
* BAQ530 - redundant with BAQ550
* FNQ530 and FNQ540 - redundant with phq questions
* SMD641 - redundant with SMQ040
* AUQ101 - redundant with AUQ054
* 'DR1_040Z', DR2_040Z' - does not represent routine behavior

In [12]:
variables_to_remove = [
    "PHQ050",
    "FSD032A", "FSD032B", "FSD032C", "FSD041", "FSD052", "FSD071", "FSD092", "FSD102",
    "BMXWT", "BMXHT",
    "ALQ111",
    "RXQ033",
    "OCQ210",
    "HUQ042",
    "DIQ180",
    "BAQ341", "BAQ421", "BAQ530",
    "FNQ530", "FNQ540",
    "SMD641",
    "AUQ101",
    'DR1_040Z', 'DR2_040Z']

In [13]:
df_copy.drop(columns=variables_to_remove, inplace=True)

In [14]:
df_copy.shape

(7587, 181)

The following fatures will be combined into single features:

* BPXOSY1 + BPXOSY2 + BPXOSY3 → systolic_bp_mean
* BPXODI1 + BPXODI2 + BPXODI3 → diastolic_bp_mean
* BPXOPLS1 + BPXOPLS2 + BPXOPLS3 → pulse_mean
* RXQ515 + RXQ520 → taking_low_dose_aspirin
* SLD012 + SLD013 → avg_sleep_hrs_per_night
* DPQ010 + DPQ020 + DPQ030 + DPQ040 + DPQ050 + DPQ060 + DPQ070 + DPQ090 → phq8_score
* BAQ321A + BAQ321B + BAQ321C + BAQ321D → num_balance_symptoms
* BAXTC11, BAXTC12, BAXTC21, BAXTC22, BAXTC31, BAXTC32, BAXTC41, BAXTC42, BAXTC51, BAXTC52 → mrt_avg
* PAD790Q + PAD790U + PAD800 → moderate_ltpa_min_per_wk
* PAD810Q + PAD810U + PAD820 → vigorous_ltpa_min_per_wk
* DR1TKCAL + DR2TKCAL → avg_energy_kcal
* DR1TPROT + DR2TPROT → avg_protein_g
* DR1TCARB + DR2TCARB → avg_carbs_g
* DR1TSUGR + DR2TSUGR → avg_sugars_g
* DR1TFIBE + DR2TFIBE → avg_fiber_g
* DR1TTFAT + DR2TTFAT → avg_total_fat_g
* DR1TSFAT + DR2TSFAT → avg_sat_fat_g
* DR1TMFAT + DR2TMFAT → avg_mono_fat_g
* DR1TPFAT + DR2TPFAT → avg_poly_fat_g
* DR1TCHOL + DR2TCHOL → avg_cholesterol_mg
* DR1TSODI + DR2TSODI → avg_sodium_mg
* DR1TCAFF + DR2TCAFF → avg_caffeine_mg
* DR1_320Z + DR2_320Z → avg_total_water_g

#### Diet
The following features represent dietary intake over 2 days. The mean of each will be calculated to get an average daily dietary intake value.

* If both days were usual = mean of day 1 and day 2
* If only day 1 was usual = just day 1's value
* If only day 2 was usual = just day 2's value
* If neither day was usual = NaN

In [15]:
day1_usual = df_copy["DR1_300"] == 2
day2_usual = df_copy["DR2_300"] == 2

nutrients = {
    "kcal":     ("DR1TKCAL", "DR2TKCAL"),
    "protein":  ("DR1TPROT", "DR2TPROT"),
    "fat":      ("DR1TTFAT", "DR2TTFAT"),
    "carbs":    ("DR1TCARB", "DR2TCARB"),
    "chol_diet":("DR1TCHOL", "DR2TCHOL"),
    "sug_diet": ("DR1TSUGR", "DR2TSUGR"),
    "caff":     ("DR1TCAFF", "DR2TCAFF"),
    "h2o":      ("DR1_320Z", "DR2_320Z"),
    "fiber":    ("DR1TFIBE", "DR2TFIBE"),
    "sat_fat":  ("DR1TSFAT", "DR2TSFAT"),
    "mono_fat": ("DR1TMFAT", "DR2TMFAT"),
    "poly_fat": ("DR1TPFAT", "DR2TPFAT"),
    "sodium_diet":   ("DR1TSODI", "DR2TSODI"),

}

for new_col, (d1_col, d2_col) in nutrients.items():
    d1 = df_copy[d1_col].where(day1_usual, other=np.nan)
    d2 = df_copy[d2_col].where(day2_usual, other=np.nan)
    df_copy[new_col] = pd.concat([d1, d2], axis=1).mean(axis=1, skipna=True)

In [16]:
df_copy[['kcal', 'protein', 'fat', 'carbs', 'chol_diet', 'sug_diet', 'caff', 'h2o',
         'fiber', 'sat_fat', 'mono_fat', 'poly_fat', 'sodium_diet']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 7587 entries, 0 to 11931
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   kcal         4341 non-null   float64
 1   protein      4341 non-null   float64
 2   fat          4341 non-null   float64
 3   carbs        4341 non-null   float64
 4   chol_diet    4341 non-null   float64
 5   sug_diet     4341 non-null   float64
 6   caff         4341 non-null   float64
 7   h2o          4341 non-null   float64
 8   fiber        4341 non-null   float64
 9   sat_fat      4341 non-null   float64
 10  mono_fat     4341 non-null   float64
 11  poly_fat     4341 non-null   float64
 12  sodium_diet  4341 non-null   float64
dtypes: float64(13)
memory usage: 829.8 KB

In [17]:
df_copy[['kcal', 'protein', 'fat', 'carbs', 'chol_diet', 'sug_diet', 'caff', 'h2o',
         'fiber', 'sat_fat', 'mono_fat', 'poly_fat', 'sodium_diet']].describe()

,kcal,protein,fat,carbs,chol_diet,sug_diet,caff,h2o,fiber,sat_fat,mono_fat,poly_fat,sodium_diet
count,4341.000000,4341.000000,4341.000000,4341.000000,4341.000000,4341.000000,4341.000000,4341.000000,4341.000000,4341.000000,4341.000000,4341.000000,4341.000000
mean,2023.733472,76.536820,85.824773,227.318621,322.340705,96.113918,151.527528,1302.827808,16.707256,27.337564,29.251478,19.962938,3179.027643
std,825.771001,34.611337,41.478041,106.100429,238.477737,63.217381,163.381179,1174.705268,9.589575,14.889609,15.322041,11.433707,1472.211532
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1479.000000,53.350000,57.830000,155.700000,154.000000,55.070000,34.000000,495.000000,10.100000,17.197000,19.138500,12.165000,2206.000000
50%,1911.500000,71.640000,80.340000,212.185000,263.000000,82.895000,114.000000,1080.000000,14.900000,24.786500,26.788000,18.068500,2943.000000
75%,2454.000000,93.370000,106.695000,279.895000,428.500000,122.485000,213.000000,1800.000000,21.000000,34.702500,36.253000,25.156000,3903.500000
max,10446.000000,325.525000,505.620000,1300.940000,3598.000000,835.095000,1828.000000,24960.000000,117.300000,208.842000,176.340000,131.548000,20006.000000

In [18]:
print((df_copy[["kcal", "protein", "fat", "carbs", "chol_diet", "sug_diet", "caff", "h2o",
                'fiber', 'sat_fat', 'mono_fat', 'poly_fat', 'sodium_diet']] == 0).sum())

kcal             2
protein          2
fat              2
carbs            2
chol_diet        9
sug_diet         2
caff           396
h2o            382
fiber            3
sat_fat          2
mono_fat         2
poly_fat         2
sodium_diet      2
dtype: int64

In [19]:
# removes respondents that had zero calories as this is likely a data error
for col in ["kcal", "protein", "fat", "carbs", "sug_diet"]:
    df_copy.loc[df_copy[col] == 0, col] = np.nan

In [20]:
# Removes extreme ouliers based on realistic thresholds for the average person

thresholds = {
    "kcal":     8000,
    "protein":  300,
    "fat":      400,
    "carbs":    1000,
    "sug_diet": 600,
    "caff":     1200,
    "h2o":      10000,
    'sodium_diet':   10000,  # ~20000mg max observed, 10000mg is very high but more plausible
}

for col, high in thresholds.items():
    df_copy.loc[df_copy[col] > high, col] = np.nan

In [21]:
df_copy[['kcal', 'protein', 'fat', 'carbs', 'chol_diet', 'sug_diet', 'caff', 'h2o', 'sodium_diet']].describe()

,kcal,protein,fat,carbs,chol_diet,sug_diet,caff,h2o,sodium_diet
count,4336.000000,4336.000000,4337.000000,4336.000000,4341.000000,4336.000000,4330.000000,4338.000000,4330.000000
mean,2019.895526,76.408966,85.684134,226.719091,322.340705,95.703336,148.316397,1291.958439,3154.250462
std,804.401373,34.030181,40.592670,102.604699,238.477737,60.772933,150.313293,1089.835192,1382.244599
min,72.000000,2.790000,1.070000,0.480000,0.000000,0.100000,0.000000,0.000000,0.000000
25%,1479.750000,53.380000,57.840000,155.715000,154.000000,55.070000,34.000000,495.000000,2202.125000
50%,1911.250000,71.630000,80.340000,212.160000,263.000000,82.892500,114.000000,1080.000000,2939.250000
75%,2452.625000,93.355000,106.690000,279.475000,428.500000,122.427500,212.000000,1800.000000,3895.250000
max,7090.000000,297.240000,377.005000,891.920000,3598.000000,596.600000,1192.000000,9570.000000,9791.000000

In [22]:
df_copy.drop(columns=["DR1TKCAL", "DR2TKCAL", "DR1TPROT", "DR2TPROT", "DR1TTFAT", "DR2TTFAT",
                      "DR1TCARB", "DR2TCARB", "DR1TCHOL", "DR2TCHOL", "DR1TSUGR", "DR2TSUGR",
                      "DR1TCAFF", "DR2TCAFF", "DR1_320Z", "DR2_320Z", "DR1_300", "DR2_300",
                      "DR1TFIBE", "DR2TFIBE", "DR1TSFAT", "DR2TSFAT", "DR1TMFAT", "DR2TMFAT",
                      "DR1TPFAT", "DR2TPFAT", "DR1TSODI", "DR2TSODI"], inplace=True)

In [23]:
df_copy.shape

(7587, 166)

#### Blood Pressure and Pulse

In [24]:
bp_di = df_copy[["BPXODI1","BPXODI2","BPXODI3"]]
bp_sys = df_copy[["BPXOSY1","BPXOSY2","BPXOSY3"]]
pulse = df_copy[["BPXOPLS1","BPXOPLS2","BPXOPLS3"]]

print(bp_di.head())
print(bp_sys.head())
print(pulse.head())

# Calculate how many rows only 3 readings
di_3_readings = bp_di.dropna(thresh=3)
sys_3_readings = bp_sys.dropna(thresh=3)
pulse_3_readings = pulse.dropna(thresh=3)

print(f"Number of rows with at least 3 diastolic readings: {di_3_readings.shape[0]}")
print(f"Number of rows with at least 3 systolic readings: {sys_3_readings.shape[0]}")
print(f"Number of rows with at least 3 pulse readings: {pulse_3_readings.shape[0]}")

# Calculate how many rows only 2 readings
di_2_readings = bp_di.dropna(thresh=2)
sys_2_readings = bp_sys.dropna(thresh=2)
pulse_2_readings = pulse.dropna(thresh=2)

print(f"Number of rows with at least 2 diastolic readings: {di_2_readings.shape[0]}")
print(f"Number of rows with at least 2 systolic readings: {sys_2_readings.shape[0]}")
print(f"Number of rows with at least 2 pulse readings: {pulse_2_readings.shape[0]}")

# Calculate how many rows only 2 readings
di_1_readings = bp_di.dropna(thresh=1)
sys_1_readings = bp_sys.dropna(thresh=1)
pulse_1_readings = pulse.dropna(thresh=1)

print(f"Number of rows with at least 1 diastolic readings: {di_1_readings.shape[0]}")
print(f"Number of rows with at least 1 systolic readings: {sys_1_readings.shape[0]}")
print(f"Number of rows with at least 1 pulse readings: {pulse_1_readings.shape[0]}")

   BPXODI1  BPXODI2  BPXODI3
0     98.0     96.0     94.0
1     84.0     76.0     76.0
2     79.0     80.0     76.0
6      NaN      NaN      NaN
7      NaN      NaN      NaN
   BPXOSY1  BPXOSY2  BPXOSY3
0    135.0    131.0    132.0
1    121.0    117.0    113.0
2    111.0    112.0    104.0
6      NaN      NaN      NaN
7      NaN      NaN      NaN
   BPXOPLS1  BPXOPLS2  BPXOPLS3
0      82.0      79.0      82.0
1      72.0      71.0      73.0
2      84.0      83.0      77.0
6       NaN       NaN       NaN
7       NaN       NaN       NaN
Number of rows with at least 3 diastolic readings: 5746
Number of rows with at least 3 systolic readings: 5746
Number of rows with at least 3 pulse readings: 5746
Number of rows with at least 2 diastolic readings: 5760
Number of rows with at least 2 systolic readings: 5760
Number of rows with at least 2 pulse readings: 5760
Number of rows with at least 1 diastolic readings: 5764
Number of rows with at least 1 systolic readings: 5764
Number of rows with at least 1 pulse readings: 5764

In [25]:
# The majority of rows have all 3 readings, but some rows have only 1 or 2 readings.

df_copy["bp_sys"] = df_copy[["BPXOSY1", "BPXOSY2", "BPXOSY3"]].mean(axis=1)
df_copy["bp_di"] = df_copy[["BPXODI1", "BPXODI2", "BPXODI3"]].mean(axis=1)
df_copy["pulse"] = df_copy[["BPXOPLS1", "BPXOPLS2", "BPXOPLS3"]].mean(axis=1)

In [26]:
df_copy[['bp_sys', 'bp_di']].describe()

            bp_sys        bp_di
count  5764.000000  5764.000000
mean    121.809218    74.732969
std      17.496136    10.941740
min      70.000000    34.000000
25%     110.000000    67.333333
50%     119.666667    74.000000
75%     131.083333    81.333333
max     232.333333   139.000000

In [27]:
df_copy.drop(columns=["BPXOSY1", "BPXOSY2", "BPXOSY3", "BPXODI1", "BPXODI2", "BPXODI3", 'BPXOPLS1', 'BPXOPLS2', 'BPXOPLS3'], inplace=True)

In [28]:
df_copy.shape

(7587, 160)

#### Physical activity

https://pmc.ncbi.nlm.nih.gov/articles/PMC7719906/

* mod_pa_min_per_wk  : Total minutes per week of moderate-intensity leisure-time physical activity (LTPA). Moderate activity is defined as causing moderate increases in breathing or heart rate.

* vig_pa_min_per_wk  : Total minutes per week of vigorous-intensity LTPA.Vigorous activity causes large increases in breathing or heart rate.

* total_pa_mets_per_wk: MET-weighted total physical activity per week, combining moderate (3.5 METs) and vigorous (7.0 METs) activity. Accounts for the greater physiological demand of vigorous activity relative to moderate activity.

* meets_pa_guidelines : Binary indicator of whether the respondent meets WHO 2020 guidelines: >=150 min/wk moderate OR >=75 min/wk vigorous intensity LTPA (1=meets guidelines, 0=does not).

In [29]:
# check counts as both minutes and hours are used
print(df_copy['PAD800'].value_counts().sort_index().head(30))
print(df_copy['PAD820'].value_counts().sort_index().head(30))

PAD800
1.0       19
2.0        7
3.0        7
4.0        2
5.0       44
6.0        3
7.0        2
8.0        1
10.0      99
11.0       2
12.0       2
14.0       1
15.0     228
16.0       2
18.0       1
20.0     345
21.0       1
23.0       2
24.0       1
25.0      46
27.0       1
29.0       1
30.0    1422
31.0       1
35.0      28
36.0       1
37.0       1
39.0       1
40.0     148
45.0     521
Name: count, dtype: int64
PAD820
1.0        12
2.0         3
3.0         6
4.0         2
5.0        33
6.0         2
7.0         1
8.0         2
10.0      101
12.0        5
15.0      181
20.0      205
25.0       28
30.0      886
32.0        1
35.0       10
40.0       67
45.0      254
46.0        1
50.0       19
55.0        3
60.0     1040
70.0        5
75.0       13
90.0      143
100.0       1
105.0       3
120.0     354
150.0       4
180.0      90
Name: count, dtype: int64

In [30]:
print(df_copy['PAD790U'].unique())
print(df_copy['PAD810U'].unique())

['W' nan 'D' 'M' 'Y']
['W' nan 'M' 'D' 'Y']

In [31]:
# Convert moderate frequency to weekly rate
df_copy['PAD790Q'] = np.where(df_copy['PAD790U'] == "b'W'", df_copy['PAD790Q'],
                     np.where(df_copy['PAD790U'] == "b'D'", df_copy['PAD790Q'] * 7,
                     np.where(df_copy['PAD790U'] == "b'M'", df_copy['PAD790Q'] / 4.33,
                     np.where(df_copy['PAD790U'] == "b'Y'", df_copy['PAD790Q'] / 52,
                     df_copy['PAD790Q']))))

# Convert vigorous frequency to weekly rate
df_copy['PAD810Q'] = np.where(df_copy['PAD810U'] == "b'W'", df_copy['PAD810Q'],
                     np.where(df_copy['PAD810U'] == "b'D'", df_copy['PAD810Q'] * 7,
                     np.where(df_copy['PAD810U'] == "b'M'", df_copy['PAD810Q'] / 4.33,
                     np.where(df_copy['PAD810U'] == "b'Y'", df_copy['PAD810Q'] / 52,
                     df_copy['PAD810Q']))))

# Compute minutes per week
df_copy['mod_pa_min_per_wk'] = df_copy['PAD790Q'] * df_copy['PAD800']
df_copy['vig_pa_min_per_wk'] = df_copy['PAD810Q'] * df_copy['PAD820']

In [32]:
df_copy[['mod_pa_min_per_wk', 'vig_pa_min_per_wk']].describe()

       mod_pa_min_per_wk  vig_pa_min_per_wk
count        6015.000000        3561.000000
mean          227.030424         160.374895
std           457.044201         290.164190
min             1.000000           1.000000
25%            60.000000          45.000000
50%           120.000000          90.000000
75%           240.000000         180.000000
max         18720.000000        6000.000000

In [33]:
(df_copy[['mod_pa_min_per_wk', 'vig_pa_min_per_wk']].isna()).sum()

mod_pa_min_per_wk    1572
vig_pa_min_per_wk    4026
dtype: int64

In [34]:
df_copy[['mod_pa_min_per_wk', 'vig_pa_min_per_wk']].describe()

       mod_pa_min_per_wk  vig_pa_min_per_wk
count        6015.000000        3561.000000
mean          227.030424         160.374895
std           457.044201         290.164190
min             1.000000           1.000000
25%            60.000000          45.000000
50%           120.000000          90.000000
75%           240.000000         180.000000
max         18720.000000        6000.000000

In [35]:
# MET-weighted total physical activity per week
df_copy['total_pa_mets_per_wk'] = (
    (df_copy['mod_pa_min_per_wk'] * 3.5) +
    (df_copy['vig_pa_min_per_wk'] * 7.0)
)

In [36]:
df_copy['total_pa_mets_per_wk'].describe()

count     3461.000000
mean      1973.164692
std       2704.922245
min         52.500000
25%        735.000000
50%       1260.000000
75%       2275.000000
max      52080.000000
Name: total_pa_mets_per_wk, dtype: float64

In [37]:
# Binary: meets WHO 2020 physical activity guidelines
df_copy['meets_pa_guidelines'] = (
    (df_copy['mod_pa_min_per_wk'] >= 150) |
    (df_copy['vig_pa_min_per_wk'] >= 75)
)

df_copy['meets_pa_guidelines'] = df_copy['meets_pa_guidelines'].where(
    df_copy[['mod_pa_min_per_wk', 'vig_pa_min_per_wk']].notna().all(axis=1)
).astype('Int64')  # keeps NA as <NA>, not 0

In [38]:
df_copy['meets_pa_guidelines'].value_counts()

meets_pa_guidelines
1    2501
0     960
Name: count, dtype: Int64

In [39]:
# Check if sedentary time is in minutes

print(df_copy['PAD680'].value_counts().sort_index().head(30))

PAD680
0.0         6
1.0         2
2.0         3
4.0         1
5.0         4
6.0         2
7.0         2
10.0        6
12.0        2
15.0       11
20.0       12
25.0        1
30.0       53
35.0        1
40.0        4
45.0        6
50.0        2
60.0      246
70.0        1
80.0        1
90.0       45
120.0     686
150.0      10
180.0     851
200.0       2
210.0       5
240.0    1042
250.0       1
300.0     842
330.0       1
Name: count, dtype: int64

In [40]:
# PAD680 Appears to be in minutes already
df_copy['PAD680'].describe()

count    7513.000000
mean      361.479702
std       209.377969
min         0.000000
25%       180.000000
50%       300.000000
75%       480.000000
max      1380.000000
Name: PAD680, dtype: float64

In [41]:
df_copy.drop(columns=['PAD800', 'PAD820', 'PAD790Q', 'PAD810Q', 'PAD790U', 'PAD810U' ], inplace=True)

In [42]:
df_copy.shape

(7587, 158)

#### Alcohol use

In [43]:
# Convert ALQ121 to drinking days per week based on codebook response categories
alq121_map = {
    0:  0,        # Never in the last year
    1:  7,        # Every day (7 days/week)
    2:  6,        # Nearly every day (~6 days/week)
    3:  3.5,      # 3 to 4 times a week
    4:  2,        # 2 times a week
    5:  1,        # Once a week
    6:  0.577,    # 2 to 3 times a month (2.5/month / 4.33)
    7:  0.231,    # Once a month (1/month / 4.33)
    8:  0.212,    # 7 to 11 times in last year (9/52)
    9:  0.087,    # 3 to 6 times in last year (4.5/52)
    10: 0.029,    # 1 to 2 times in last year (1.5/52)
}

df_copy['ALQ121'] = df_copy['ALQ121'].replace(alq121_map)

# Calculate drinks per week
df_copy['drinks_per_week'] = np.where(
    df_copy['ALQ121'] == 0,
    0,
    df_copy['ALQ121'] * df_copy['ALQ130']
)

In [44]:
df_copy[['drinks_per_week']].describe()

       drinks_per_week
count      4640.000000
mean          3.905298
std           8.085078
min           0.000000
25%           0.058000
50%           0.577000
75%           4.000000
max          98.000000

In [45]:
df_copy.drop(columns=['ALQ121', 'ALQ130'], inplace=True)

In [46]:
df_copy.shape

(7587, 157)

In [47]:
# Cap at 70 drinks per week (10 per day)
df_copy.loc[df_copy['drinks_per_week'] > 70, 'drinks_per_week'] = np.nan

#### Sleep

In [48]:
# avg_sleep_hrs = weighted average of weekday and weekend sleep hours
df_copy['avg_sleep_hrs'] = (
    (df_copy['SLD012'] * 5 + df_copy['SLD013'] * 2) / 7
)

In [49]:
df_copy[['avg_sleep_hrs']].describe()

       avg_sleep_hrs
count    7370.000000
mean        7.860545
std         1.388003
min         3.000000
25%         7.000000
50%         8.000000
75%         8.642857
max        13.500000

In [50]:
df_copy.drop(columns=['SLD012', 'SLD013'], inplace=True)

In [51]:
df_copy.shape

(7587, 156)

#### Depression score

In [52]:
# phq8_score: sum of 8 PHQ depression items (0-24), higher = more severe symptoms
phq_cols = ['DPQ010', 'DPQ020', 'DPQ030', 'DPQ040',
            'DPQ050', 'DPQ060', 'DPQ070', 'DPQ090']

df_copy['phq8_score'] = df_copy[phq_cols].sum(axis=1, skipna=False)

In [53]:
df_copy[['phq8_score']].value_counts()

phq8_score
0.0           1273
1.0            699
2.0            648
3.0            501
4.0            363
5.0            300
6.0            262
7.0            207
8.0            163
9.0            134
10.0           129
11.0            92
12.0            81
13.0            74
15.0            46
17.0            43
14.0            40
16.0            32
18.0            27
21.0            19
20.0            15
19.0            14
22.0            11
23.0             5
24.0             2
Name: count, dtype: int64

In [54]:
df_copy.drop(columns=phq_cols, inplace=True)

In [55]:
df_copy.shape

(7587, 149)

#### Aspirin Use

In [56]:
# taking_low_dose_aspirin: 1 if doctor-advised or self-initiated low-dose aspirin use
df_copy['taking_aspirin'] = (
    (df_copy['RXQ515'] == 1) | (df_copy['RXQ520'] == 0)
).astype(int)

In [57]:
df_copy['taking_aspirin'].value_counts()

taking_aspirin
0    6302
1    1285
Name: count, dtype: int64

In [58]:
df_copy.drop(columns=['RXQ515', 'RXQ520'], inplace=True)

In [59]:
df_copy.shape

(7587, 148)

#### Balance

In [60]:
# Average two trials per condition (uses trial 1 if trial 2 is missing)
df_copy['romberg_c1_time'] = df_copy[['BAXTC11', 'BAXTC12']].mean(axis=1, skipna=True)
df_copy['romberg_c2_time'] = df_copy[['BAXTC21', 'BAXTC22']].mean(axis=1, skipna=True)
df_copy['romberg_c3_time'] = df_copy[['BAXTC31', 'BAXTC32']].mean(axis=1, skipna=True)
df_copy['romberg_c4_time'] = df_copy[['BAXTC41', 'BAXTC42']].mean(axis=1, skipna=True)
df_copy['romberg_c5_time'] = df_copy[['BAXTC51', 'BAXTC52']].mean(axis=1, skipna=True)

time_cols = ['romberg_c1_time', 'romberg_c2_time', 'romberg_c3_time',
             'romberg_c4_time', 'romberg_c5_time']

# Count conditions attempted
df_copy['romberg_conditions_attempted'] = df_copy[time_cols].notna().sum(axis=1)

# Fill unattempted conditions with 0, then divide by 5
df_copy['romberg_avg_time'] = (
    df_copy[time_cols].fillna(0).sum(axis=1) / 5
)

In [61]:
(df_copy['romberg_avg_time'].isna()).sum()

0

In [62]:
# Set to NaN for people who didn't attempt any conditions
df_copy['romberg_avg_time'] = np.where(
    df_copy['romberg_conditions_attempted'] == 0,
    np.nan,
    df_copy['romberg_avg_time'])

In [63]:
df_copy['romberg_avg_time'].describe()

count    3951.000000
mean       19.374918
std         4.450179
min         0.200000
25%        16.600000
50%        20.000000
75%        24.000000
max        24.000000
Name: romberg_avg_time, dtype: float64

In [64]:
df_copy.drop(columns=time_cols + ['romberg_c1_time', 'romberg_c2_time', 'romberg_c3_time',
                                  'romberg_c4_time', 'romberg_c5_time', 'BAXTC11', 'BAXTC12',
                                  'BAXTC21', 'BAXTC22', 'BAXTC31', 'BAXTC32', 'BAXTC41',
                                  'BAXTC42', 'BAXTC51', 'BAXTC52',
                                   'romberg_conditions_attempted'],
             inplace=True)

In [65]:
df_copy.shape

(7587, 139)

In [66]:
df_copy.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Index: 7587 entries, 0 to 11931
Data columns (total 139 columns):
 #    Column                Dtype
---   ------                -----
 0    SEQN                  float64
 1    LBXVIDMS              float64
 2    LBXSATSI              float64
 3    LBXSAL                float64
 4    LBXSAPSI              float64
 5    LBXSASSI              float64
 6    LBXSBU                float64
 7    LBXSCK                float64
 8    LBDSCRSI              float64
 9    LBXSGTSI              float64
 10   LBXMAGN               float64
 11   LBXSPH                float64
 12   LBXSKSI               float64
 13   LBXSNASI              float64
 14   LBXSCA                float64
 15   LBXSTP                float64
 16   LBXSUA                float64
 17   LBXHSCRP              float64
 18   LBXGH                 float64
 19   LBDFOT                float64
 20   LBXFER                float64
 21   LBXWBCSI              float64
 22   LBXHGB                float64
 23   LBXHCT                float64
 24   LBXTC                 float64
 25   LBXTLG                float64
 26   LBDLDLN               float64
 27   LBDHDD                float64
 28   RHQ131                float64
 29   RHD167                float64
 30   RXQ050                float64
 31   OCD150                float64
 32   OCQ180                float64
 33   OCQ215                float64
 34   MCQ035                float64
 35   AGQ030                float64
 36   MCQ053                float64
 37   MCQ195                float64
 38   MCQ500                float64
 39   OSQ230                float64
 40   KIQ022                float64
 41   KIQ005                float64
 42   KIQ481                float64
 43   HUQ010                float64
 44   HUQ030                float64
 45   HUQ090                float64
 46   HIQ011                float64
 47   DIQ010                float64
 48   DIQ070                float64
 49   BAQ110                float64
 50   BAQ121                float64
 51   BAQ125                float64
 52   BAQ132                float64
 53   BAQ140                float64
 54   BAQ150                float64
 55   BAQ160                float64
 56   BAQ201                float64
 57   DBD100                float64
 58   DRQSPREP              float64
 59   DRQSDIET              float64
 60   DRD340                float64
 61   DRD360                float64
 62   FNQ410                float64
 63   FNQ430                float64
 64   FNQ440                float64
 65   FNQ450                float64
 66   FNQ460                float64
 67   FNQ490                float64
 68   FNQ510                float64
 69   FNQ520                float64
 70   RIAGENDR              float64
 71   RIDAGEYR              float64
 72   RIDRETH3              float64
 73   RIDEXMON              float64
 74   DMDMARTZ              float64
 75   RIDEXPRG              float64
 76   INDFMPIR              float64
 77   BAQ321A               float64
 78   BAQ321B               float64
 79   BAQ321C               float64
 80   BAQ321D               float64
 81   BAQ391A               float64
 82   BAQ391B               float64
 83   BAQ401                float64
 84   BAQ550                float64
 85   BAQ560                float64
 86   BPQ150                float64
 87   BPQ101D               float64
 88   SMQ681                float64
 89   SMQ846                float64
 90   SMQ851                float64
 91   FSDAD                 float64
 92   SMD470                float64
 93   SMQ040                float64
 94   SMD650                float64
 95   PAD680                float64
 96   OHQ845                float64
 97   DSD010                float64
 98   DSD010AN              float64
 99   DEQ034A               float64
 100  DEQ034C               float64
 101  DEQ034D               float64
 102  AUQ054                float64
 103  ALQ142                float64
 104  ALQ280                float64
 105  BMXBMI                float64
 106  DSQTFA                float64
 107  DSQTVB12              float64
 108  DSQTVD                float64
 109  DSQTCALC              float64
 110  DSQTPHOS              float64
 111  DSQTMAGN              float64
 112  DSQTIRON              float64
 113  DSQTPOTA              float64
 114  kcal                  float64
 115  protein               float64
 116  fat                   float64
 117  carbs                 float64
 118  chol_diet             float64
 119  sug_diet              float64
 120  caff                  float64
 121  h2o                   float64
 122  fiber                 float64
 123  sat_fat               float64
 124  mono_fat              float64
 125  poly_fat              float64
 126  sodium_diet           float64
 127  bp_sys                float64
 128  bp_di                 float64
 129  pulse                 float64
 130  mod_pa_min_per_wk     float64
 131  vig_pa_min_per_wk     float64
 132  total_pa_mets_per_wk  float64
 133  meets_pa_guidelines   Int64
 134  drinks_per_week       float64
 135  avg_sleep_hrs         float64
 136  phq8_score            float64
 137  taking_aspirin        int32
 138  romberg_avg_time      float64
dtypes: Int64(1), float64(137), int32(1)
memory usage: 8.1 MB

#### Rename Columns

In [67]:
# NHANES Variable Rename Dictionary

nhanes_rename = {

    # IDENTIFIERS & DEMOGRAPHICS  (DEMO_L)
    "SEQN":      "respondent_id",
    "RIAGENDR":  "gender",
    "RIDAGEYR":  "age_years",
    "RIDRETH3":  "race_ethnicity",
    "RIDEXMON":  "exam_season",
    "DMDMARTZ":  "marital_status",
    "RIDEXPRG":  "pregnancy_status_exam",
    "INDFMPIR":  "income_poverty_ratio",

    # LAB: BIOCHEMISTRY PANEL  (BIOPRO_L)
    "LBXVIDMS":  "vitamin_d",
    "LBXSATSI":  "alt",
    "LBXSAL":    "albumin",
    "LBXSAPSI":  "alp",
    "LBXSASSI":  "ast",
    "LBXSBU":    "bun",
    "LBXSCK":    "creatine_kinase",
    "LBDSCRSI":  "creatinine_serum",
    "LBXSGTSI":  "ggt",
    "LBXMAGN":   "magnesium",
    "LBXSPH":    "phosphorus",
    "LBXSKSI":   "potassium",
    "LBXSNASI":  "sodium",
    "LBXSCA":    "calcium",
    "LBXSTP":    "total_protein",
    "LBXSUA":    "uric_acid",

    # LAB: OTHER
    "LBXHSCRP":  "hscrp",
    "LBXGH":     "hba1c",
    "LBDFOT":    "folate",
    "LBXFER":    "ferritin",
    "LBXWBCSI":  "wbc",
    "LBXHGB":    "hemoglobin",
    "LBXHCT":    "hematocrit",
    "LBXTC":     "cholesterol_total",
    "LBXTLG":    "triglycerides",
    "LBDLDLN":   "ldl_cholesterol",
    "LBDHDD":    "hdl_cholesterol",

    # REPRODUCTIVE HEALTH  (RHQ_L)
    "RHQ131":    "ever_been_pregnant",
    "RHD167":    "total_deliveries",

    # PRESCRIPTION MEDICATIONS  (RXQ_RX_L)
    "RXQ050":    "num_rx_drugs",

    # OCCUPATION  (OCQ_L)
    "OCD150":    "work_status_last_week",
    "OCQ180":    "hours_worked_last_week",
    "OCQ215":    "days_worked_per_week",

    # MEDICAL CONDITIONS  (MCQ_L)
    "MCQ035":    "still_have_asthma",
    "AGQ030":    "had_hay_fever_past_yr",
    "MCQ053":    "taking_anemia_treatment_past_3mo",
    "MCQ195":    "type_of_arthritis",
    "MCQ500":    "told_have_liver_condition",
    "OSQ230":    "metal_objects_in_body",

    # KIDNEY CONDITIONS / UROLOGY  (KIQ_U_L)
    "KIQ022":    "told_weak_failing_kidneys",
    "KIQ005":    "urinary_leakage_frequency",
    "KIQ481":    "times_per_night_urinating",

    # HOSPITAL UTILIZATION & ACCESS  (HUQ_L)
    "HUQ010":    "self_rated_health",
    "HUQ030":    "has_routine_healthcare_place",
    "HUQ090":    "mental_health_professional_past_yr",


    # HEALTH INSURANCE  (HIQ_L)
    "HIQ011":    "has_health_insurance",

    # DIABETES  (DIQ_L)
    "DIQ010":    "told_have_diabetes",
    "DIQ070":    "takes_diabetes_pills",

    # BALANCE QUESTIONNAIRE  (BAQ_L)
    "BAQ110":    "dizziness_or_balance_problem_past_yr",
    "BAQ121":    "dizziness_duration",
    "BAQ125":    "dizziness_type",
    "BAQ132":    "dizziness_causes_fall",
    "BAQ140":    "has_balance_problem",
    "BAQ150":    "balance_problem_affects_daily_life",
    "BAQ160":    "seen_dr_for_balance",
    "BAQ201":    "cause_of_balance_problem",
    "BAQ321A":   "vertigo_past_12mo",
    "BAQ321B":   "blurring_vision_past_12mo",
    "BAQ321C":   "unsteadiness_past_12mo",
    "BAQ321D":   "lightheadedness_past_12mo",
    "BAQ391A":   "episodes_with_nausea_vomiting",
    "BAQ391B":   "episodes_with_migraine_headache",
    "BAQ401":    "balance_prevented_usual_activities",
    "BAQ421":    "severity_of_balance_problem",
    "BAQ550":    "falls_past_12_months",
    "BAQ560":    "fall_injury_past_12_months",

    # DIETARY BEHAVIOR  (DBQ_L)
    "DBD100":    "salt_used_at_table",
    "DRQSPREP":  "salt_used_in_cooking",
    "DRQSDIET":  "on_special_diet",
    "DRD340":    "ate_shellfish_past_30_days",
    "DRD360":    "ate_fish_past_30_days",

    # FOOD SECURITY  (FSQ_L)
    "FSDAD":     "food_security_category",

    # BLOOD PRESSURE & CHOLESTEROL  (BPQ_L)
    "BPQ150":    "taking_bp_medication",
    "BPQ101D":   "taking_cholesterol_medication",

    # SMOKING  (SMQ_L, SMQRTU_L, SMQFAM_L)
    "SMQ040":    "current_smoker_status",
    "SMD650":    "avg_cigarettes_per_day",
    "SMQ681":    "smoked_tobacco_past_5_days",
    "SMQ846":    "used_e_cigarette_past_5_days",
    "SMQ851":    "used_smokeless_tobacco_past_5_days",
    "SMD470":    "num_smokers_in_household",

    # ORAL HEALTH  (OHQ_L)
    "OHQ845":    "oral_health",

    # DIETARY SUPPLEMENTS  (DSQTOT_L)
    "DSD010":    "took_dietary_supplements_past_30_days",
    "DSD010AN":  "took_nonprescription_antacids",

    # DERMATOLOGY / SUN EXPOSURE  (DEQ_L)
    "DEQ034A":   "freq_stay_in_shade",
    "DEQ034C":   "freq_wear_long_sleeves",
    "DEQ034D":   "freq_use_sunscreen",

    # AUDIOMETRY  (AUQ_L)
    "AUQ054":    "hearing_condition",

    # ALCOHOL USE  (ALQ_L)
    "ALQ142":    "days_4_or_more_drinks",
    "ALQ280":    "days_8_or_more_drinks",

    # BODY MEASURES  (BMX_L)
    "BMXBMI":    "bmi",

    # FUNCTIONING  (FNQ_L)
    "FNQ410":    "difficulty_seeing",
    "FNQ430":    "difficulty_hearing",
    "FNQ440":    "difficulty_walking_climbing_steps",
    "FNQ450":    "difficulty_communicating",
    "FNQ460":    "difficulty_remembering_concentrating",
    "FNQ490":    "difficulty_using_hands_fingers",
    "FNQ510":    "freq_worried_nervous_anxious",
    "FNQ520":    "level_worried_nervous_anxious",
    "FNQ530":    "freq_feeling_depressed",
    "FNQ540":    "level_feeling_depressed",

    # SUPPLEMENTS (DSQTOT_L)
    "DSQTFA":    "taking_folic_acid",
    "DSQTVB12":   "taking_vitamin_b12",
    "DSQTVD":    "taking_vitamin_d",
    "DSQTIRON":  "taking_iron",
    "DSQTPOTA":  "taking_potassium",
    "DSQTMAGN":  "taking_magnesium",
    "DSQTCALC":    "taking_calcium",
    "DSQTPHOS":  "taking_phosphorus",

    # SEDENTART TIME
    'PAD680' :   'sedentary_time_per_day'

}

In [68]:
# rename columns using the rename_dict
df_copy = df_copy.rename(columns=nhanes_rename)

In [69]:
df_copy.head()

,respondent_id,vitamin_d,alt,albumin,alp,ast,bun,creatine_kinase,creatinine_serum,ggt,...,pulse,mod_pa_min_per_wk,vig_pa_min_per_wk,total_pa_mets_per_wk,meets_pa_guidelines,drinks_per_week,avg_sleep_hrs,phq8_score,taking_aspirin,romberg_avg_time
0,130378.0,58.9,39.0,4.3,91.0,25.0,11.0,172.0,70.72,41.0,...,81.000000,135.0,135.0,1417.5,1,NaN,9.357143,NaN,0,15.0
1,130379.0,60.5,17.0,3.9,64.0,20.0,24.0,98.0,69.84,31.0,...,72.000000,180.0,135.0,1575.0,1,18.000,9.000000,1.0,0,20.1
2,130380.0,39.4,13.0,3.7,78.0,15.0,10.0,38.0,56.58,44.0,...,81.333333,20.0,NaN,NaN,<NA>,0.029,8.285714,2.0,0,12.3
6,130384.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,<NA>,NaN,7.642857,NaN,0,NaN
7,130385.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,90.0,60.0,735.0,0,NaN,8.000000,NaN,0,NaN

In [70]:
print(df_copy.describe())

       respondent_id    vitamin_d          alt      albumin          alp  \
count    7587.000000  5479.000000  5319.000000  5361.000000  5325.000000
mean   136383.516937    79.781480    22.021057     4.087372    84.782160
std      3441.231341    37.576195    16.729535     0.347624    28.389502
min    130378.000000     9.130000     3.000000     2.200000    20.000000
25%    133398.500000    53.900000    13.000000     3.900000    66.000000
50%    136426.000000    75.000000    18.000000     4.100000    80.000000
75%    139358.000000    98.800000    26.000000     4.300000    98.000000
max    142309.000000   424.000000   350.000000     5.500000   458.000000

               ast          bun  creatine_kinase  creatinine_serum  \
count  5307.000000  5325.000000      5319.000000       5324.000000
mean     22.568683    14.774085       147.292536         78.216993
std      14.934785     5.390311       299.447482         34.676202
min       6.000000     4.000000        10.000000         30.940000
25%      16.000000    11.000000        69.000000         63.650000
50%      20.000000    14.000000       100.000000         74.260000
75%      25.000000    17.000000       157.000000         87.520000
max     518.000000    74.000000     16837.000000       1341.030000

               ggt  ...        pulse  mod_pa_min_per_wk  vig_pa_min_per_wk  \
count  5325.000000  ...  5764.000000        6015.000000        3561.000000
mean     30.117559  ...    71.676093         227.030424         160.374895
std      47.184618  ...    12.079336         457.044201         290.164190
min       2.000000  ...    34.000000           1.000000           1.000000
25%      13.000000  ...    63.333333          60.000000          45.000000
50%      20.000000  ...    70.666667         120.000000          90.000000
75%      31.000000  ...    79.000000         240.000000         180.000000
max    1541.000000  ...   129.333333       18720.000000        6000.000000

       total_pa_mets_per_wk  meets_pa_guidelines  drinks_per_week  \
count           3461.000000               3461.0      4634.000000
mean            1973.164692             0.722624         3.803751
std             2704.922245             0.447769         7.574702
min               52.500000                  0.0         0.000000
25%              735.000000                  0.0         0.058000
50%             1260.000000                  1.0         0.577000
75%             2275.000000                  1.0         4.000000
max            52080.000000                  1.0        70.000000

       avg_sleep_hrs   phq8_score  taking_aspirin  romberg_avg_time
count    7370.000000  5180.000000     7587.000000       3951.000000
mean        7.860545     3.970270        0.169369         19.374918
std         1.388003     4.494734        0.375102          4.450179
min         3.000000     0.000000        0.000000          0.200000
25%         7.000000     1.000000        0.000000         16.600000
50%         8.000000     2.000000        0.000000         20.000000
75%         8.642857     6.000000        0.000000         24.000000
max        13.500000    24.000000        1.000000         24.000000

[8 rows x 139 columns]

# Feature Engineering

In [71]:
# Mean arterial pressure (MAP)

# Mean Arterial Pressure (MAP) formula calculates average blood pressure using systolic (SBP) and diastolic (DBP) readings
# MAP = 1/3*(SBP) + 2/3*(DBP)

df_copy['map'] = 1/3 * df_copy['bp_sys'] + 2/3 * df_copy['bp_di']

In [72]:
df_copy['map'].describe()

count    5764.000000
mean       90.425052
std        11.937270
min        51.333333
25%        82.333333
50%        89.333333
75%        97.111111
max       155.888889
Name: map, dtype: float64

In [73]:
# Daily macronutrient percentages of total caloric intake
# Protein: 1g = 4kcal, Carbs: 1g = 4kcal, Fat, 1g = 9kcal https://caloriedata.org/calculators/macro-calculator

df_copy['carbs_pct'] = (df_copy['carbs'] * 4) / df_copy['kcal'] * 100
df_copy['fat_pct'] = (df_copy['fat'] * 9) / df_copy['kcal'] * 100
df_copy['protein_pct'] = (df_copy['protein'] * 4) / df_copy['kcal'] * 100

In [74]:
df_copy[['carbs_pct', 'fat_pct', 'protein_pct']].describe()

         carbs_pct      fat_pct  protein_pct
count  4336.000000  4335.000000  4333.000000
mean     45.122325    37.841830    15.471334
std      10.171058     8.517320     4.488791
min       1.981591     1.936709     2.680773
25%      38.584328    32.508741    12.447359
50%      45.136665    37.945020    14.881149
75%      51.539203    43.208694    17.831190
max      93.825137    68.536047    39.753805

In [75]:
df_copy['fiber_per_1000kcal'] = df_copy['fiber'] / df_copy['kcal'] * 1000

In [76]:
print(df_copy.columns.tolist())

['respondent_id', 'vitamin_d', 'alt', 'albumin', 'alp', 'ast', 'bun', 'creatine_kinase', 'creatinine_serum', 'ggt', 'magnesium', 'phosphorus', 'potassium', 'sodium', 'calcium', 'total_protein', 'uric_acid', 'hscrp', 'hba1c', 'folate', 'ferritin', 'wbc', 'hemoglobin', 'hematocrit', 'cholesterol_total', 'triglycerides', 'ldl_cholesterol', 'hdl_cholesterol', 'ever_been_pregnant', 'total_deliveries', 'num_rx_drugs', 'work_status_last_week', 'hours_worked_last_week', 'days_worked_per_week', 'still_have_asthma', 'had_hay_fever_past_yr', 'taking_anemia_treatment_past_3mo', 'type_of_arthritis', 'told_have_liver_condition', 'metal_objects_in_body', 'told_weak_failing_kidneys', 'urinary_leakage_frequency', 'times_per_night_urinating', 'self_rated_health', 'has_routine_healthcare_place', 'mental_health_professional_past_yr', 'has_health_insurance', 'told_have_diabetes', 'takes_diabetes_pills', 'dizziness_or_balance_problem_past_yr', 'dizziness_duration', 'dizziness_type', 'dizziness_causes_fall', 'has_balance_problem', 'balance_problem_affects_daily_life', 'seen_dr_for_balance', 'cause_of_balance_problem', 'salt_used_at_table', 'salt_used_in_cooking', 'on_special_diet', 'ate_shellfish_past_30_days', 'ate_fish_past_30_days', 'difficulty_seeing', 'difficulty_hearing', 'difficulty_walking_climbing_steps', 'difficulty_communicating', 'difficulty_remembering_concentrating', 'difficulty_using_hands_fingers', 'freq_worried_nervous_anxious', 'level_worried_nervous_anxious', 'gender', 'age_years', 'race_ethnicity', 'exam_season', 'marital_status', 'pregnancy_status_exam', 'income_poverty_ratio', 'vertigo_past_12mo', 'blurring_vision_past_12mo', 'unsteadiness_past_12mo', 'lightheadedness_past_12mo', 'episodes_with_nausea_vomiting', 'episodes_with_migraine_headache', 'balance_prevented_usual_activities', 'falls_past_12_months', 'fall_injury_past_12_months', 'taking_bp_medication', 'taking_cholesterol_medication', 'smoked_tobacco_past_5_days', 'used_e_cigarette_past_5_days', 'used_smokeless_tobacco_past_5_days', 'food_security_category', 'num_smokers_in_household', 'current_smoker_status', 'avg_cigarettes_per_day', 'sedentary_time_per_day', 'oral_health', 'took_dietary_supplements_past_30_days', 'took_nonprescription_antacids', 'freq_stay_in_shade', 'freq_wear_long_sleeves', 'freq_use_sunscreen', 'hearing_condition', 'days_4_or_more_drinks', 'days_8_or_more_drinks', 'bmi', 'taking_folic_acid', 'taking_vitamin_b12', 'taking_vitamin_d', 'taking_calcium', 'taking_phosphorus', 'taking_magnesium', 'taking_iron', 'taking_potassium', 'kcal', 'protein', 'fat', 'carbs', 'chol_diet', 'sug_diet', 'caff', 'h2o', 'fiber', 'sat_fat', 'mono_fat', 'poly_fat', 'sodium_diet', 'bp_sys', 'bp_di', 'pulse', 'mod_pa_min_per_wk', 'vig_pa_min_per_wk', 'total_pa_mets_per_wk', 'meets_pa_guidelines', 'drinks_per_week', 'avg_sleep_hrs', 'phq8_score', 'taking_aspirin', 'romberg_avg_time', 'map', 'carbs_pct', 'fat_pct', 'protein_pct', 'fiber_per_1000kcal']

# Variable types

In [77]:
# Get column types and store in dictionary
var_type = pd.read_csv('nhanes_codebook_artifact.csv')
# var_type = pd.read_csv('/content/drive/MyDrive/DSA601/blood_draft/models/nhanes_codebook_artifact.csv')
mapping = dict(zip(var_type['column_name'], var_type['var_type']))

In [78]:
# reverse column renaming dictionary to get original column names
# used to retrieve variable type from nhanes_codebook_artifact

nhanes_rename = {

    # IDENTIFIERS & DEMOGRAPHICS  (DEMO_L)
    "SEQN":      "respondent_id",
    "RIAGENDR":  "gender",
    "RIDAGEYR":  "age_years",
    "RIDRETH3":  "race_ethnicity",
    "RIDEXMON":  "exam_season",
    "DMDMARTZ":  "marital_status",
    "RIDEXPRG":  "pregnancy_status_exam",
    "INDFMPIR":  "income_poverty_ratio",

    # LAB: BIOCHEMISTRY PANEL  (BIOPRO_L)
    "LBXVIDMS":  "vitamin_d",
    "LBXSATSI":  "alt",
    "LBXSAL":    "albumin",
    "LBXSAPSI":  "alp",
    "LBXSASSI":  "ast",
    "LBXSBU":    "bun",
    "LBXSCK":    "creatine_kinase",
    "LBDSCRSI":  "creatinine_serum",
    "LBXSGTSI":  "ggt",
    "LBXMAGN":   "magnesium",
    "LBXSPH":    "phosphorus",
    "LBXSKSI":   "potassium",
    "LBXSNASI":  "sodium",
    "LBXSCA":    "calcium",
    "LBXSTP":    "total_protein",
    "LBXSUA":    "uric_acid",

    # LAB: OTHER
    "LBXHSCRP":  "hscrp",
    "LBXGH":     "hba1c",
    "LBDFOT":    "folate",
    "LBXFER":    "ferritin",
    "LBXWBCSI":  "wbc",
    "LBXHGB":    "hemoglobin",
    "LBXHCT":    "hematocrit",
    "LBXTC":     "cholesterol_total",
    "LBXTLG":    "triglycerides",
    "LBDLDLN":   "ldl_cholesterol",
    "LBDHDD":    "hdl_cholesterol",

    # REPRODUCTIVE HEALTH  (RHQ_L)
    "RHQ131":    "ever_been_pregnant",
    "RHD167":    "total_deliveries",

    # PRESCRIPTION MEDICATIONS  (RXQ_RX_L)
    "RXQ050":    "num_rx_drugs",

    # OCCUPATION  (OCQ_L)
    "OCD150":    "work_status_last_week",
    "OCQ180":    "hours_worked_last_week",
    "OCQ215":    "days_worked_per_week",

    # MEDICAL CONDITIONS  (MCQ_L)
    "MCQ035":    "still_have_asthma",
    "AGQ030":    "had_hay_fever_past_yr",
    "MCQ053":    "taking_anemia_treatment_past_3mo",
    "MCQ195":    "type_of_arthritis",
    "MCQ500":    "told_have_liver_condition",
    "OSQ230":    "metal_objects_in_body",

    # KIDNEY CONDITIONS / UROLOGY  (KIQ_U_L)
    "KIQ022":    "told_weak_failing_kidneys",
    "KIQ005":    "urinary_leakage_frequency",
    "KIQ481":    "times_per_night_urinating",

    # HOSPITAL UTILIZATION & ACCESS  (HUQ_L)
    "HUQ010":    "self_rated_health",
    "HUQ030":    "has_routine_healthcare_place",
    "HUQ090":    "mental_health_professional_past_yr",


    # HEALTH INSURANCE  (HIQ_L)
    "HIQ011":    "has_health_insurance",

    # DIABETES  (DIQ_L)
    "DIQ010":    "told_have_diabetes",
    "DIQ070":    "takes_diabetes_pills",

    # BALANCE QUESTIONNAIRE  (BAQ_L)
    "BAQ110":    "dizziness_or_balance_problem_past_yr",
    "BAQ121":    "dizziness_duration",
    "BAQ125":    "dizziness_type",
    "BAQ132":    "dizziness_causes_fall",
    "BAQ140":    "has_balance_problem",
    "BAQ150":    "balance_problem_affects_daily_life",
    "BAQ160":    "seen_dr_for_balance",
    "BAQ201":    "cause_of_balance_problem",
    "BAQ321A":   "vertigo_past_12mo",
    "BAQ321B":   "blurring_vision_past_12mo",
    "BAQ321C":   "unsteadiness_past_12mo",
    "BAQ321D":   "lightheadedness_past_12mo",
    "BAQ391A":   "episodes_with_nausea_vomiting",
    "BAQ391B":   "episodes_with_migraine_headache",
    "BAQ401":    "balance_prevented_usual_activities",
    "BAQ421":    "severity_of_balance_problem",
    "BAQ550":    "falls_past_12_months",
    "BAQ560":    "fall_injury_past_12_months",

    # DIETARY BEHAVIOR  (DBQ_L)
    "DBD100":    "salt_used_at_table",
    "DRQSPREP":  "salt_used_in_cooking",
    "DRQSDIET":  "on_special_diet",
    "DRD340":    "ate_shellfish_past_30_days",
    "DRD360":    "ate_fish_past_30_days",

    # FOOD SECURITY  (FSQ_L)
    "FSDAD":     "food_security_category",

    # BLOOD PRESSURE & CHOLESTEROL  (BPQ_L)
    "BPQ150":    "taking_bp_medication",
    "BPQ101D":   "taking_cholesterol_medication",

    # SMOKING  (SMQ_L, SMQRTU_L, SMQFAM_L)
    "SMQ040":    "current_smoker_status",
    "SMD650":    "avg_cigarettes_per_day",
    "SMQ681":    "smoked_tobacco_past_5_days",
    "SMQ846":    "used_e_cigarette_past_5_days",
    "SMQ851":    "used_smokeless_tobacco_past_5_days",
    "SMD470":    "num_smokers_in_household",

    # ORAL HEALTH  (OHQ_L)
    "OHQ845":    "oral_health",

    # DIETARY SUPPLEMENTS  (DSQTOT_L)
    "DSD010":    "took_dietary_supplements_past_30_days",
    "DSD010AN":  "took_nonprescription_antacids",

    # DERMATOLOGY / SUN EXPOSURE  (DEQ_L)
    "DEQ034A":   "freq_stay_in_shade",
    "DEQ034C":   "freq_wear_long_sleeves",
    "DEQ034D":   "freq_use_sunscreen",

    # AUDIOMETRY  (AUQ_L)
    "AUQ054":    "hearing_condition",

    # ALCOHOL USE  (ALQ_L)
    "ALQ142":    "days_4_or_more_drinks",
    "ALQ280":    "days_8_or_more_drinks",

    # BODY MEASURES  (BMX_L)
    "BMXBMI":    "bmi",

    # FUNCTIONING  (FNQ_L)
    "FNQ410":    "difficulty_seeing",
    "FNQ430":    "difficulty_hearing",
    "FNQ440":    "difficulty_walking_climbing_steps",
    "FNQ450":    "difficulty_communicating",
    "FNQ460":    "difficulty_remembering_concentrating",
    "FNQ490":    "difficulty_using_hands_fingers",
    "FNQ510":    "freq_worried_nervous_anxious",
    "FNQ520":    "level_worried_nervous_anxious",
    "FNQ530":    "freq_feeling_depressed",
    "FNQ540":    "level_feeling_depressed",

    # SUPPLEMENTS (DSQTOT_L)
    "DSQTFA":    "taking_folic_acid",
    "DSQTVB12":   "taking_vitamin_b12",
    "DSQTVD":    "taking_vitamin_d",
    "DSQTIRON":  "taking_iron",
    "DSQTPOTA":  "taking_potassium",
    "DSQTMAGN":  "taking_magnesium",
    "DSQTCALC":    "taking_calcium",
    "DSQTPHOS":  "taking_phosphorus",

    # SEDENTART TIME
    'PAD680' :   'sedentary_time_per_day'

}

inverse_rename = {v: k for k, v in nhanes_rename.items()}

In [79]:
# maps df_copy columns to vartypes
vartype_dict = {
    col: mapping[inverse_rename[col]]
    for col in df_copy.columns
    if col in inverse_rename and inverse_rename[col] in mapping
}

In [80]:
vartype_dict

{'respondent_id': 'identifier',
 'vitamin_d': 'continuous',
 'alt': 'continuous',
 'albumin': 'continuous',
 'alp': 'continuous',
 'ast': 'continuous',
 'bun': 'continuous',
 'creatine_kinase': 'continuous',
 'creatinine_serum': 'continuous',
 'ggt': 'continuous',
 'magnesium': 'continuous',
 'phosphorus': 'continuous',
 'potassium': 'continuous',
 'sodium': 'continuous',
 'calcium': 'continuous',
 'total_protein': 'continuous',
 'uric_acid': 'continuous',
 'hscrp': 'continuous',
 'hba1c': 'continuous',
 'folate': 'continuous',
 'ferritin': 'continuous',
 'wbc': 'continuous',
 'hemoglobin': 'continuous',
 'hematocrit': 'continuous',
 'cholesterol_total': 'continuous',
 'triglycerides': 'continuous',
 'ldl_cholesterol': 'continuous',
 'hdl_cholesterol': 'continuous',
 'ever_been_pregnant': 'binary',
 'total_deliveries': 'continuous',
 'num_rx_drugs': 'ordinal',
 'work_status_last_week': 'ordinal',
 'hours_worked_last_week': 'continuous',
 'days_worked_per_week': 'continuous',
 'still_have_asthma': 'binary',
 'had_hay_fever_past_yr': 'binary',
 'taking_anemia_treatment_past_3mo': 'binary',
 'type_of_arthritis': 'categorical',
 'told_have_liver_condition': 'binary',
 'metal_objects_in_body': 'binary',
 'told_weak_failing_kidneys': 'binary',
 'urinary_leakage_frequency': 'ordinal',
 'times_per_night_urinating': 'ordinal',
 'self_rated_health': 'ordinal',
 'has_routine_healthcare_place': 'ordinal',
 'mental_health_professional_past_yr': 'binary',
 'has_health_insurance': 'binary',
 'told_have_diabetes': 'ordinal',
 'takes_diabetes_pills': 'binary',
 'dizziness_or_balance_problem_past_yr': 'binary',
 'dizziness_duration': 'binary',
 'dizziness_type': 'binary',
 'dizziness_causes_fall': 'binary',
 'has_balance_problem': 'binary',
 'balance_problem_affects_daily_life': 'binary',
 'seen_dr_for_balance': 'binary',
 'cause_of_balance_problem': 'binary',
 'salt_used_at_table': 'ordinal',
 'salt_used_in_cooking': 'ordinal',
 'on_special_diet': 'binary',
 'ate_shellfish_past_30_days': 'binary',
 'ate_fish_past_30_days': 'binary',
 'difficulty_seeing': 'ordinal',
 'difficulty_hearing': 'ordinal',
 'difficulty_walking_climbing_steps': 'ordinal',
 'difficulty_communicating': 'ordinal',
 'difficulty_remembering_concentrating': 'ordinal',
 'difficulty_using_hands_fingers': 'ordinal',
 'freq_worried_nervous_anxious': 'ordinal',
 'level_worried_nervous_anxious': 'ordinal',
 'gender': 'binary',
 'age_years': 'continuous',
 'race_ethnicity': 'ordinal',
 'exam_season': 'binary',
 'marital_status': 'ordinal',
 'pregnancy_status_exam': 'ordinal',
 'income_poverty_ratio': 'continuous',
 'vertigo_past_12mo': 'binary',
 'blurring_vision_past_12mo': 'binary',
 'unsteadiness_past_12mo': 'binary',
 'lightheadedness_past_12mo': 'binary',
 'episodes_with_nausea_vomiting': 'binary',
 'episodes_with_migraine_headache': 'binary',
 'balance_prevented_usual_activities': 'binary',
 'falls_past_12_months': 'ordinal',
 'fall_injury_past_12_months': 'binary',
 'taking_bp_medication': 'binary',
 'taking_cholesterol_medication': 'binary',
 'smoked_tobacco_past_5_days': 'binary',
 'used_e_cigarette_past_5_days': 'binary',
 'used_smokeless_tobacco_past_5_days': 'binary',
 'food_security_category': 'ordinal',
 'num_smokers_in_household': 'ordinal',
 'current_smoker_status': 'ordinal',
 'avg_cigarettes_per_day': 'continuous',
 'sedentary_time_per_day': 'continuous',
 'oral_health': 'ordinal',
 'took_dietary_supplements_past_30_days': 'binary',
 'took_nonprescription_antacids': 'binary',
 'freq_stay_in_shade': 'ordinal',
 'freq_wear_long_sleeves': 'ordinal',
 'freq_use_sunscreen': 'ordinal',
 'hearing_condition': 'ordinal',
 'days_4_or_more_drinks': 'ordinal',
 'days_8_or_more_drinks': 'ordinal',
 'bmi': 'continuous',
 'taking_folic_acid': 'continuous',
 'taking_vitamin_b12': 'continuous',
 'taking_vitamin_d': 'continuous',
 'taking_calcium': 'continuous',
 'taking_phosphorus': 'continuous',
 'taking_magnesium': 'continuous',
 'taking_iron': 'continuous',
 'taking_potassium': 'continuous'}

In [81]:
# creates a DataFrame with variable names and their types from the mapping dictionary
var_groups = pd.DataFrame({
    'variable': list(vartype_dict.keys()),
    'type': list(vartype_dict.values())
})
var_groups

                                  variable         type
0                            respondent_id   identifier
1                                vitamin_d   continuous
2                                      alt   continuous
3                                  albumin   continuous
4                                      alp   continuous
5                                      ast   continuous
6                                      bun   continuous
7                          creatine_kinase   continuous
8                         creatinine_serum   continuous
9                                      ggt   continuous
10                               magnesium   continuous
11                              phosphorus   continuous
12                               potassium   continuous
13                                  sodium   continuous
14                                 calcium   continuous
15                           total_protein   continuous
16                               uric_acid   continuous
17                                   hscrp   continuous
18                                   hba1c   continuous
19                                  folate   continuous
20                                ferritin   continuous
21                                     wbc   continuous
22                              hemoglobin   continuous
23                              hematocrit   continuous
24                       cholesterol_total   continuous
25                           triglycerides   continuous
26                         ldl_cholesterol   continuous
27                         hdl_cholesterol   continuous
28                      ever_been_pregnant       binary
29                        total_deliveries   continuous
30                            num_rx_drugs      ordinal
31                   work_status_last_week      ordinal
32                  hours_worked_last_week   continuous
33                    days_worked_per_week   continuous
34                       still_have_asthma       binary
35                   had_hay_fever_past_yr       binary
36        taking_anemia_treatment_past_3mo       binary
37                       type_of_arthritis  categorical
38               told_have_liver_condition       binary
39                   metal_objects_in_body       binary
40               told_weak_failing_kidneys       binary
41               urinary_leakage_frequency      ordinal
42               times_per_night_urinating      ordinal
43                       self_rated_health      ordinal
44            has_routine_healthcare_place      ordinal
45      mental_health_professional_past_yr       binary
46                    has_health_insurance       binary
47                      told_have_diabetes      ordinal
48                    takes_diabetes_pills       binary
49    dizziness_or_balance_problem_past_yr       binary
50                      dizziness_duration       binary
51                          dizziness_type       binary
52                   dizziness_causes_fall       binary
53                     has_balance_problem       binary
54      balance_problem_affects_daily_life       binary
55                     seen_dr_for_balance       binary
56                cause_of_balance_problem       binary
57                      salt_used_at_table      ordinal
58                    salt_used_in_cooking      ordinal
59                         on_special_diet       binary
60              ate_shellfish_past_30_days       binary
61                   ate_fish_past_30_days       binary
62                       difficulty_seeing      ordinal
63                      difficulty_hearing      ordinal
64       difficulty_walking_climbing_steps      ordinal
65                difficulty_communicating      ordinal
66    difficulty_remembering_concentrating      ordinal
67          difficulty_using_hands_fingers      ordinal
68            freq_worried_nervous_anxious      ordinal
69           level_worried_nervous_anxious      ordinal
70                                  gender       binary
71                               age_years   continuous
72                          race_ethnicity      ordinal
73                             exam_season       binary
74                          marital_status      ordinal
75                   pregnancy_status_exam      ordinal
76                    income_poverty_ratio   continuous
77                       vertigo_past_12mo       binary
78               blurring_vision_past_12mo       binary
79                  unsteadiness_past_12mo       binary
80               lightheadedness_past_12mo       binary
81           episodes_with_nausea_vomiting       binary
82         episodes_with_migraine_headache       binary
83      balance_prevented_usual_activities       binary
84                    falls_past_12_months      ordinal
85              fall_injury_past_12_months       binary
86                    taking_bp_medication       binary
87           taking_cholesterol_medication       binary
88              smoked_tobacco_past_5_days       binary
89            used_e_cigarette_past_5_days       binary
90      used_smokeless_tobacco_past_5_days       binary
91                  food_security_category      ordinal
92                num_smokers_in_household      ordinal
93                   current_smoker_status      ordinal
94                  avg_cigarettes_per_day   continuous
95                  sedentary_time_per_day   continuous
96                             oral_health      ordinal
97   took_dietary_supplements_past_30_days       binary
98           took_nonprescription_antacids       binary
99                      freq_stay_in_shade      ordinal
100                 freq_wear_long_sleeves      ordinal
101                     freq_use_sunscreen      ordinal
102                      hearing_condition      ordinal
103                  days_4_or_more_drinks      ordinal
104                  days_8_or_more_drinks      ordinal
105                                    bmi   continuous
106                      taking_folic_acid   continuous
107                     taking_vitamin_b12   continuous
108                       taking_vitamin_d   continuous
109                         taking_calcium   continuous
110                      taking_phosphorus   continuous
111                       taking_magnesium   continuous
112                            taking_iron   continuous
113                       taking_potassium   continuous

In [82]:
cont_var = ( var_groups[var_groups['type'] == 'continuous']['variable'].tolist()
            + ['kcal', 'protein', 'fat', 'carbs', 'chol_diet', 'sug_diet', 'caff', 'h2o',
               'fiber', 'sat_fat', 'mono_fat', 'poly_fat', 'sodium_diet', 'bp_sys', 'bp_di',
               'pulse', 'mod_pa_min_per_wk', 'vig_pa_min_per_wk', 'total_pa_mets_per_wk',
               'drinks_per_week', 'avg_sleep_hrs', 'phq8_score', 'romberg_avg_time', 'map',
               'carbs_pct', 'fat_pct', 'protein_pct', 'fiber_per_1000kcal']) # adds continuous engineered features

bin_var = ( var_groups[var_groups['type'] == 'binary']['variable'].tolist()
            + ['meets_pa_guidelines', 'taking_aspirin']) # adds binary engineered features

cat_var = (var_groups[var_groups['type'] == 'categorical']['variable'].tolist())

ord_var = (var_groups[var_groups['type'] == 'ordinal']['variable'].tolist())

In [83]:
len(cont_var) + len(bin_var) + len(cat_var) + len(ord_var)

143

In [84]:
len(df_copy.columns)

144

In [85]:
all_listed = set(cont_var + bin_var + cat_var + ord_var)
df_cols = set(df_copy.columns)

missing_in_lists = df_cols - all_listed
missing_in_df = all_listed - df_cols

print("In df but NOT in lists:", missing_in_lists)
print("In lists but NOT in df:", missing_in_df)

In df but NOT in lists: {'respondent_id'}
In lists but NOT in df: set()

In [86]:
# gets raw codes for ordinal features to look up via nhanes_explorer
for k in ord_var:
    print(inverse_rename.get(k))

RXQ050
OCD150
KIQ005
KIQ481
HUQ010
HUQ030
DIQ010
DBD100
DRQSPREP
FNQ410
FNQ430
FNQ440
FNQ450
FNQ460
FNQ490
FNQ510
FNQ520
RIDRETH3
DMDMARTZ
RIDEXPRG
BAQ550
FSDAD
SMD470
SMQ040
OHQ845
DEQ034A
DEQ034C
DEQ034D
AUQ054
ALQ142
ALQ280

In [87]:
# The following are not true ordinal
# FNQ520, RIDRETH3, DMDMARTZ, DEQ034A, ALQ142, ALQ280

In [88]:
for k in ['FNQ520', 'RIDRETH3', 'DMDMARTZ', 'DEQ034A', 'ALQ142', 'ALQ280']:
    print(nhanes_rename.get(k))

level_worried_nervous_anxious
race_ethnicity
marital_status
freq_stay_in_shade
days_4_or_more_drinks
days_8_or_more_drinks

In [89]:
# FNQ520 (level_worried_nervous_anxious)
# Current: 1	A little, 2	A lot, 3	Somewhere in between a little and a lot
# New: 1 A little, 3	Somewhere in between a little and a lot, 3 A lot
recode_map = {1: 1, 3: 2, 2: 3}
df_copy['level_worried_nervous_anxious'] = df_copy['level_worried_nervous_anxious'].map(recode_map)

In [90]:
# DEQ034A (freq_stay_in_shade)
# Current: 1	Always, 2	Most of the time, 3	Sometimes, 4 Rarely, 5 Never, 6	Don't go out in the sun
# New: 1 Don't go out in the sun, 2	Always, 3	Most of the time, 4	Sometimes, 5 Rarely, 6 Never
recode_map = {1:2, 2:3 , 3:4, 4:5, 5:6, 6:1}
df_copy['freq_stay_in_shade'] = df_copy['freq_stay_in_shade'].map(recode_map)

In [91]:
# ALQ142 (days_4_or_more_drinks)
# Current: 0	Never in the last year, 1	Every day, 2	Nearly every day, 3	3 to 4 times a week, 4	2 times a week,
# 5	Once a week, 6	2 to 3 times a month, 7	Once a month, 8	7 to 11 times in the last year, 9	3 to 6 times in the last year, 10	1 to 2 times in the last year

# New: 1	Every day, 2	Nearly every day, 3	3 to 4 times a week, 4	2 times a week,
# 5	Once a week, 6	2 to 3 times a month, 7	Once a month, 8	7 to 11 times in the last year, 9	3 to 6 times in the last year,
# 10	1 to 2 times in the last year, 11	Never in the last year,

recode_map = {0:11, 1:1, 2:2, 3:3, 4:4, 5:5, 6:6, 7:7, 8:8, 9:9, 10:10}
df_copy['days_4_or_more_drinks'] = df_copy['days_4_or_more_drinks'].map(recode_map)

In [92]:
# ALQ280 (days_8_or_more_drinks)
# Current: 0	Never in the last year, 1	Every day, 2	Nearly every day, 3	3 to 4 times a week, 4	2 times a week,
# 5	Once a week, 6	2 to 3 times a month, 7	Once a month, 8	7 to 11 times in the last year, 9	3 to 6 times in the last year, 10	1 to 2 times in the last year

# New: 1	Every day, 2	Nearly every day, 3	3 to 4 times a week, 4	2 times a week,
# 5	Once a week, 6	2 to 3 times a month, 7	Once a month, 8	7 to 11 times in the last year, 9	3 to 6 times in the last year,
# 10	1 to 2 times in the last year, 11	Never in the last year,

recode_map = {0:11, 1:1, 2:2, 3:3, 4:4, 5:5, 6:6, 7:7, 8:8, 9:9, 10:10}
df_copy['days_8_or_more_drinks'] = df_copy['days_8_or_more_drinks'].map(recode_map)

In [93]:
# 'RIDRETH3' (race_ethnicity) and 'DMDMARTZ'(marital_status) are categorical not ordinal
ord_var.remove('race_ethnicity')
ord_var.remove('marital_status')
cat_var.append('race_ethnicity')
cat_var.append('marital_status')

In [94]:
print("Ordinal Features:", ord_var)
print("Binary Features:", bin_var)
print("Categorical Features:", cat_var)

Ordinal Features: ['num_rx_drugs', 'work_status_last_week', 'urinary_leakage_frequency', 'times_per_night_urinating', 'self_rated_health', 'has_routine_healthcare_place', 'told_have_diabetes', 'salt_used_at_table', 'salt_used_in_cooking', 'difficulty_seeing', 'difficulty_hearing', 'difficulty_walking_climbing_steps', 'difficulty_communicating', 'difficulty_remembering_concentrating', 'difficulty_using_hands_fingers', 'freq_worried_nervous_anxious', 'level_worried_nervous_anxious', 'pregnancy_status_exam', 'falls_past_12_months', 'food_security_category', 'num_smokers_in_household', 'current_smoker_status', 'oral_health', 'freq_stay_in_shade', 'freq_wear_long_sleeves', 'freq_use_sunscreen', 'hearing_condition', 'days_4_or_more_drinks', 'days_8_or_more_drinks']
Binary Features: ['ever_been_pregnant', 'still_have_asthma', 'had_hay_fever_past_yr', 'taking_anemia_treatment_past_3mo', 'told_have_liver_condition', 'metal_objects_in_body', 'told_weak_failing_kidneys', 'mental_health_professional_past_yr', 'has_health_insurance', 'takes_diabetes_pills', 'dizziness_or_balance_problem_past_yr', 'dizziness_duration', 'dizziness_type', 'dizziness_causes_fall', 'has_balance_problem', 'balance_problem_affects_daily_life', 'seen_dr_for_balance', 'cause_of_balance_problem', 'on_special_diet', 'ate_shellfish_past_30_days', 'ate_fish_past_30_days', 'gender', 'exam_season', 'vertigo_past_12mo', 'blurring_vision_past_12mo', 'unsteadiness_past_12mo', 'lightheadedness_past_12mo', 'episodes_with_nausea_vomiting', 'episodes_with_migraine_headache', 'balance_prevented_usual_activities', 'fall_injury_past_12_months', 'taking_bp_medication', 'taking_cholesterol_medication', 'smoked_tobacco_past_5_days', 'used_e_cigarette_past_5_days', 'used_smokeless_tobacco_past_5_days', 'took_dietary_supplements_past_30_days', 'took_nonprescription_antacids', 'meets_pa_guidelines', 'taking_aspirin']
Categorical Features: ['type_of_arthritis', 'race_ethnicity', 'marital_status']

In [95]:
# gets raw codes for binary features
for k in bin_var:
    print(inverse_rename.get(k))

RHQ131
MCQ035
AGQ030
MCQ053
MCQ500
OSQ230
KIQ022
HUQ090
HIQ011
DIQ070
BAQ110
BAQ121
BAQ125
BAQ132
BAQ140
BAQ150
BAQ160
BAQ201
DRQSDIET
DRD340
DRD360
RIAGENDR
RIDEXMON
BAQ321A
BAQ321B
BAQ321C
BAQ321D
BAQ391A
BAQ391B
BAQ401
BAQ560
BPQ150
BPQ101D
SMQ681
SMQ846
SMQ851
DSD010
DSD010AN
None
None

In [96]:
print(df_copy['meets_pa_guidelines'].unique())
print(df_copy['taking_aspirin'].unique())

<IntegerArray>
[1, <NA>, 0]
Length: 3, dtype: Int64
[0 1]

In [97]:
for k in cat_var:
    print(inverse_rename.get(k))

MCQ195
RIDRETH3
DMDMARTZ

In [98]:
# Create new dictionary with renamed columns and variable type
type_map = {}

for col in cont_var:
    type_map[col] = "continuous"

for col in bin_var:
    type_map[col] = "binary"

for col in cat_var:
    type_map[col] = "categorical"

for col in ord_var:
    type_map[col] = "ordinal"

In [99]:
nahnes_var_types = pd.DataFrame({
    "Column Name": df_copy.columns,
    "Type": [type_map.get(col, "NA") for col in df_copy.columns]
})

In [100]:
len(nahnes_var_types)

144

In [101]:
len(df_copy.columns)

144

In [102]:
print(cat_var)

['type_of_arthritis', 'race_ethnicity', 'marital_status']

In [103]:
df_copy.head()

,respondent_id,vitamin_d,alt,albumin,alp,ast,bun,creatine_kinase,creatinine_serum,ggt,...,drinks_per_week,avg_sleep_hrs,phq8_score,taking_aspirin,romberg_avg_time,map,carbs_pct,fat_pct,protein_pct,fiber_per_1000kcal
0,130378.0,58.9,39.0,4.3,91.0,25.0,11.0,172.0,70.72,41.0,...,NaN,9.357143,NaN,0,15.0,108.222222,31.592806,30.703597,25.474820,4.280576
1,130379.0,60.5,17.0,3.9,64.0,20.0,24.0,98.0,69.84,31.0,...,18.000,9.000000,1.0,0,20.1,91.444444,45.150332,26.512779,13.301670,9.720266
2,130380.0,39.4,13.0,3.7,78.0,15.0,10.0,38.0,56.58,44.0,...,0.029,8.285714,2.0,0,12.3,88.555556,56.559078,28.885591,15.473199,12.334294
6,130384.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.642857,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
7,130385.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8.000000,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [104]:
# Remove these columns to reduce noise
to_drop = ['type_of_arthritis',
    'has_routine_healthcare_place',
    'metal_objects_in_body',
    'on_special_diet',
    'episodes_with_migraine_headache',
    'balance_prevented_usual_activities',
    'took_dietary_supplements_past_30_days']

df_copy.drop(columns = to_drop, inplace=True)

In [105]:
print(nahnes_var_types)
print("Number of Columns in df_copy:", len(df_copy.columns))

                               Column Name         Type
0                            respondent_id           NA
1                                vitamin_d   continuous
2                                      alt   continuous
3                                  albumin   continuous
4                                      alp   continuous
5                                      ast   continuous
6                                      bun   continuous
7                          creatine_kinase   continuous
8                         creatinine_serum   continuous
9                                      ggt   continuous
10                               magnesium   continuous
11                              phosphorus   continuous
12                               potassium   continuous
13                                  sodium   continuous
14                                 calcium   continuous
15                           total_protein   continuous
16                               uric_acid   continuous
17                                   hscrp   continuous
18                                   hba1c   continuous
19                                  folate   continuous
20                                ferritin   continuous
21                                     wbc   continuous
22                              hemoglobin   continuous
23                              hematocrit   continuous
24                       cholesterol_total   continuous
25                           triglycerides   continuous
26                         ldl_cholesterol   continuous
27                         hdl_cholesterol   continuous
28                      ever_been_pregnant       binary
29                        total_deliveries   continuous
30                            num_rx_drugs      ordinal
31                   work_status_last_week      ordinal
32                  hours_worked_last_week   continuous
33                    days_worked_per_week   continuous
34                       still_have_asthma       binary
35                   had_hay_fever_past_yr       binary
36        taking_anemia_treatment_past_3mo       binary
37                       type_of_arthritis  categorical
38               told_have_liver_condition       binary
39                   metal_objects_in_body       binary
40               told_weak_failing_kidneys       binary
41               urinary_leakage_frequency      ordinal
42               times_per_night_urinating      ordinal
43                       self_rated_health      ordinal
44            has_routine_healthcare_place      ordinal
45      mental_health_professional_past_yr       binary
46                    has_health_insurance       binary
47                      told_have_diabetes      ordinal
48                    takes_diabetes_pills       binary
49    dizziness_or_balance_problem_past_yr       binary
50                      dizziness_duration       binary
51                          dizziness_type       binary
52                   dizziness_causes_fall       binary
53                     has_balance_problem       binary
54      balance_problem_affects_daily_life       binary
55                     seen_dr_for_balance       binary
56                cause_of_balance_problem       binary
57                      salt_used_at_table      ordinal
58                    salt_used_in_cooking      ordinal
59                         on_special_diet       binary
60              ate_shellfish_past_30_days       binary
61                   ate_fish_past_30_days       binary
62                       difficulty_seeing      ordinal
63                      difficulty_hearing      ordinal
64       difficulty_walking_climbing_steps      ordinal
65                difficulty_communicating      ordinal
66    difficulty_remembering_concentrating      ordinal
67          difficulty_using_hands_fingers      ordinal
68            freq_worried_nervous_anxious      ordinal
69           level_worried_nervous_anxious      ordinal
70                                  gender       binary
71                               age_years   continuous
72                          race_ethnicity  categorical
73                             exam_season       binary
74                          marital_status  categorical
75                   pregnancy_status_exam      ordinal
76                    income_poverty_ratio   continuous
77                       vertigo_past_12mo       binary
78               blurring_vision_past_12mo       binary
79                  unsteadiness_past_12mo       binary
80               lightheadedness_past_12mo       binary
81           episodes_with_nausea_vomiting       binary
82         episodes_with_migraine_headache       binary
83      balance_prevented_usual_activities       binary
84                    falls_past_12_months      ordinal
85              fall_injury_past_12_months       binary
86                    taking_bp_medication       binary
87           taking_cholesterol_medication       binary
88              smoked_tobacco_past_5_days       binary
89            used_e_cigarette_past_5_days       binary
90      used_smokeless_tobacco_past_5_days       binary
91                  food_security_category      ordinal
92                num_smokers_in_household      ordinal
93                   current_smoker_status      ordinal
94                  avg_cigarettes_per_day   continuous
95                  sedentary_time_per_day   continuous
96                             oral_health      ordinal
97   took_dietary_supplements_past_30_days       binary
98           took_nonprescription_antacids       binary
99                      freq_stay_in_shade      ordinal
100                 freq_wear_long_sleeves      ordinal
101                     freq_use_sunscreen      ordinal
102                      hearing_condition      ordinal
103                  days_4_or_more_drinks      ordinal
104                  days_8_or_more_drinks      ordinal
105                                    bmi   continuous
106                      taking_folic_acid   continuous
107                     taking_vitamin_b12   continuous
108                       taking_vitamin_d   continuous
109                         taking_calcium   continuous
110                      taking_phosphorus   continuous
111                       taking_magnesium   continuous
112                            taking_iron   continuous
113                       taking_potassium   continuous
114                                   kcal   continuous
115                                protein   continuous
116                                    fat   continuous
117                                  carbs   continuous
118                              chol_diet   continuous
119                               sug_diet   continuous
120                                   caff   continuous
121                                    h2o   continuous
122                                  fiber   continuous
123                                sat_fat   continuous
124                               mono_fat   continuous
125                               poly_fat   continuous
126                            sodium_diet   continuous
127                                 bp_sys   continuous
128                                  bp_di   continuous
129                                  pulse   continuous
130                      mod_pa_min_per_wk   continuous
131                      vig_pa_min_per_wk   continuous
132                   total_pa_mets_per_wk   continuous
133                    meets_pa_guidelines       binary
134                        drinks_per_week   continuous
135                          avg_sleep_hrs   continuous
136                             phq8_score   continuous
137                         taking_aspirin       binary
138                       romberg_avg_time   continuous
139                                    map   continuous
140                              carbs_pct   continuous
141                                fat_pct   continuous
142                            protein_pct   continuous
143                     fiber_per_1000kcal   continuous
Number of Columns in df_copy: 137

In [106]:
df_copy.head()

,respondent_id,vitamin_d,alt,albumin,alp,ast,bun,creatine_kinase,creatinine_serum,ggt,...,drinks_per_week,avg_sleep_hrs,phq8_score,taking_aspirin,romberg_avg_time,map,carbs_pct,fat_pct,protein_pct,fiber_per_1000kcal
0,130378.0,58.9,39.0,4.3,91.0,25.0,11.0,172.0,70.72,41.0,...,NaN,9.357143,NaN,0,15.0,108.222222,31.592806,30.703597,25.474820,4.280576
1,130379.0,60.5,17.0,3.9,64.0,20.0,24.0,98.0,69.84,31.0,...,18.000,9.000000,1.0,0,20.1,91.444444,45.150332,26.512779,13.301670,9.720266
2,130380.0,39.4,13.0,3.7,78.0,15.0,10.0,38.0,56.58,44.0,...,0.029,8.285714,2.0,0,12.3,88.555556,56.559078,28.885591,15.473199,12.334294
6,130384.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.642857,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
7,130385.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8.000000,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [107]:
for col in bin_var:
  if col in df_copy.columns:
    print(df_copy[col].unique())

[nan  0.  1.]
[nan  1.  0.]
[ 1.  0. nan]
[ 1.  0. nan]
[nan  1.  0.]
[ 1. nan  0.]
[ 1.  0. nan]
[ 0.  1. nan]
[nan  0.  1.]
[ 0. nan  1.]
[ 1. nan  0.]
[ 1. nan  0.]
[ 1. nan  0.]
[ 1.  0. nan]
[ 1.  0. nan]
[ 1. nan  0.]
[ 0. nan  1.]
[ 0. nan  1.]
[ 0. nan  1.]
[0. 1.]
[ 1.  0. nan]
[ 1.  0. nan]
[ 1.  0. nan]
[ 1.  0. nan]
[ 1.  0. nan]
[nan  0.  1.]
[nan  1.  0.]
[ 0. nan  1.]
[ 1.  0. nan]
[nan  1.  0.]
[nan  1.  0.]
[nan  1.  0.]
[ 1. nan  0.]
<IntegerArray>
[1, <NA>, 0]
Length: 3, dtype: Int64
[0 1]

In [108]:
df_copy['triglycerides'].unique()

array([ 153.,   86.,  375.,   nan,  142.,   57.,  108.,  146.,   84.,
        150.,   91.,   81.,  379.,  157.,   69.,  284.,   98.,   58.,
         90.,  131.,   70.,   60.,   78.,   61.,   65.,   82.,   59.,
        254.,  187.,   87.,   47.,   68.,   75.,   51.,  158.,  196.,
        130.,   95.,  198.,  487.,  225.,  307.,   55.,  105.,   77.,
         92.,  100.,  199.,  110.,  182.,   39.,  113.,   46.,  201.,
         40.,   48.,   96.,  292.,   88.,  124.,  273.,  170.,   43.,
        280.,  188.,   71.,  104.,   74.,  144.,  154.,  120.,  136.,
        115.,  117.,  263.,  180.,   49.,  308.,  162.,  116.,  143.,
         76.,  147.,   89.,  102.,   73.,   54.,  109.,  121.,   99.,
        164.,  169.,  212.,  107.,   83.,  111.,  185.,   44.,   85.,
        119.,   32.,   42.,  276.,  264.,  148.,   56.,   93.,  101.,
         64.,  220.,  186.,  106.,   79.,   94.,  156.,  351.,  204.,
        126.,  310.,   97.,  203.,  177.,   52.,  272.,  195.,  135.,
        194.,   66.,   53.,  192.,  172.,  166.,  309.,   67.,  258.,
        202.,  410.,  389.,  141.,   38.,  137.,  293.,   80.,  122.,
         62.,  222.,  319.,  200.,  197.,   50.,   45.,  114.,  134.,
        287.,  210.,  213.,  127.,  128.,  112.,  233.,   27.,  208.,
        151.,  152.,   63.,  224.,  123.,  250.,   72.,  125.,  149.,
        215.,  160.,  241.,  163.,   34.,  330.,  214.,  229.,  345.,
        245.,  145.,  176.,  132.,   28.,  669.,  317.,  118.,  165.,
        240.,  189.,  129.,  168.,  206.,  301.,  161.,  205.,  209.,
        138.,  251.,  183.,  237.,  275.,   41.,  155.,  103.,  674.,
        235.,  289.,  384.,  174.,  382.,  249.,  218.,  140.,  171.,
        244.,  262.,  159.,   37.,  221.,  327.,   36.,  133.,  184.,
        181.,  239.,  227.,  577.,  234.,  297.,  296.,  139.,  663.,
        228.,  167.,  444.,  236.,  488.,  231.,   25.,   29.,  219.,
        216.,  322.,  179.,  259.,  299.,  230.,  178.,  267.,  207.,
        644.,  478.,  173.,  223.,  269.,  381.,  305.,   30.,  316.,
        247.,  406.,   35.,  370.,  246.,  411.,  193.,  252.,  232.,
        318.,  356.,  346.,  271.,  511.,  298., 1132.,  569.,  615.,
        331.,  226.,  498.,  191.,   31.,  348.,  323., 1745.,  442.,
        211.,  391.,  238.,  175.,  385.,  282.,  190.,   33.,  528.,
        399.,  279.,  243.,  336.,  364., 1658.,  549.,  315.,  265.,
         19.,  482.,  432.,  260.,  274.,  460.,  295.,  536.,  278.,
        255.,  462.,  397.,  652.,  683.,  586.,  248.,  338.,  217.,
        288.,  445.,  303.,  324.,  416.,  359.,  466.,  311.,  333.,
        334.,  800.,  268.,  783.])

In [109]:
# ═══════════════════════════════════════════════════════
# MULTICOLLINEARITY AUDIT — ALL 12 TARGETS
# ═══════════════════════════════════════════════════════

from scipy.stats import spearmanr
import pandas as pd
import numpy as np

# ── Define all 12 blood test targets ────────────────────
# Add all targets and their clinical thresholds here
TARGETS = {
    "triglycerides":     150,
    "hba1c":             6.5,
    "vitamin_d":         20,
    "alt":               40,
    "albumin":           3.5,
    "alp":               120,
    "ast":               40,
    "bun":               20,
    "hdl_cholesterol":   40,
    "ldl_cholesterol":   130,
    "cholesterol_total": 200,
    "hscrp":             3,
}

# ── Define competing feature groups ─────────────────────
feature_groups = {
    "fiber": {
        "features":  ["fiber", "fiber_per_1000kcal"],
        "rationale": "per_1000kcal normalizes for total intake"
    },
    "fat_total": {
        "features":  ["fat", "fat_pct"],
        "rationale": "pct normalizes for total intake"
    },
    "carbs": {
        "features":  ["carbs", "carbs_pct"],
        "rationale": "pct normalizes for total intake"
    },
    "protein": {
        "features":  ["protein", "protein_pct"],
        "rationale": "pct normalizes for total intake"
    },
    "blood_pressure": {
        "features":  ["bp_sys", "bp_di", "map"],
        "rationale": "map is linear combination of bp_sys and bp_di"
    },
    "physical_activity": {
        "features":  ["mod_pa_min_per_wk", "vig_pa_min_per_wk",
                      "total_pa_mets_per_wk", "meets_pa_guidelines",
                      "sedentary_time_per_day"],
        "rationale": "mets combines mod and vig; sedentary is independent"
    },
    "fat_subtypes": {
        "features":  ["sat_fat", "mono_fat", "poly_fat", "fat_pct"],
        "rationale": "subtypes may add independent signal beyond total pct"
    },
    "calories": {
        "features":  ["kcal", "fat_pct", "carbs_pct", "protein_pct"],
        "rationale": "pct features absorb kcal information"
    }
}

# ── Run Spearman correlation against all targets ─────────
results = []

for target_name, threshold in TARGETS.items():
    if target_name not in df_copy.columns:
        continue

    for group_name, group_info in feature_groups.items():
        for feat in group_info["features"]:
            if feat not in df_copy.columns:
                continue

            combined = df_copy[[feat, target_name]].dropna()
            missing  = df_copy[feat].isna().mean() * 100

            if len(combined) < 100:
                continue

            corr, p = spearmanr(combined[feat], combined[target_name])

            results.append({
                "target":    target_name,
                "group":     group_name,
                "feature":   feat,
                "abs_corr":  abs(corr),
                "corr":      corr,
                "p_value":   p,
                "missing":   missing,
                "n":         len(combined)
            })

results_df = pd.DataFrame(results)

# ── Summary table — best feature per group per target ───
print("=" * 70)
print("BEST FEATURE PER GROUP PER TARGET")
print("=" * 70)

# For each group find which feature wins most often across targets
group_winners = {}

for group_name in feature_groups.keys():
    group_df = results_df[results_df["group"] == group_name]
    if group_df.empty:
        continue

    print(f"\n{'─'*70}")
    print(f"GROUP: {group_name}")
    print(f"Rationale: {feature_groups[group_name]['rationale']}")
    print(f"{'─'*70}")
    print(f"{'Target':<25} {'Winner':<25} {'Corr':>8} {'Runner-up':<25} {'Corr':>8}")
    print(f"{'-'*95}")

    win_counts = {f: 0 for f in feature_groups[group_name]["features"]}

    for target_name in TARGETS.keys():
        target_group = group_df[group_df["target"] == target_name]
        if target_group.empty:
            continue

        # Sort by absolute correlation
        sorted_group = target_group.sort_values("abs_corr", ascending=False)
        if len(sorted_group) < 1:
            continue

        winner     = sorted_group.iloc[0]
        runner_up  = sorted_group.iloc[1] if len(sorted_group) > 1 else None

        win_counts[winner["feature"]] = \
            win_counts.get(winner["feature"], 0) + 1

        runner_str = (f"{runner_up['feature']:<25} "
                      f"{runner_up['corr']:>8.4f}"
                      if runner_up is not None else "")

        # Flag if winner and runner-up are very close
        close = ""
        if runner_up is not None:
            diff = winner["abs_corr"] - runner_up["abs_corr"]
            close = " ≈" if diff < 0.02 else ""

        print(f"  {target_name:<23} {winner['feature']:<25} "
              f"{winner['corr']:>8.4f} {runner_str}{close}")

    # Overall winner for this group
    overall_winner = max(win_counts, key=win_counts.get)
    print(f"\n  → Wins across targets: "
          + ", ".join([f"{f}: {c}" for f, c in
                       sorted(win_counts.items(),
                              key=lambda x: x[1],
                              reverse=True)]))
    group_winners[group_name] = overall_winner
    print(f"  → Recommended to KEEP: {overall_winner}")

# ── Final recommendation ─────────────────────────────────
print("\n" + "=" * 70)
print("FINAL RECOMMENDATIONS")
print("=" * 70)

keep    = []
drop    = []

for group_name, group_info in feature_groups.items():
    winner   = group_winners.get(group_name)
    features = group_info["features"]

    for feat in features:
        if feat not in df_copy.columns:
            continue
        missing = df_copy[feat].isna().mean() * 100

        # Keep winner unless missingness is too high
        if feat == winner:
            if missing < 50:
                keep.append(feat)
                print(f"  KEEP: {feat:<30} "
                      f"(winner in {group_name}, {missing:.1f}% missing)")
            else:
                # High missingness — check runner up
                print(f"  WARNING: {feat:<26} won in {group_name} "
                      f"but {missing:.1f}% missing — review manually")
        else:
            drop.append(feat)

# Remove duplicates — a feature might appear in multiple groups
keep = list(set(keep))
drop = [f for f in list(set(drop)) if f not in keep]

print(f"\nFeatures to KEEP ({len(keep)}): {sorted(keep)}")
print(f"Features to DROP ({len(drop)}): {sorted(drop)}")

# ── Add to DROP_COLS ─────────────────────────────────────
print("\n" + "=" * 70)
print("UPDATED DROP_COLS ADDITION")
print("=" * 70)
print("\nAdd these to your DROP_COLS list:")
print(f"REDUNDANT_FEATURES = {sorted(drop)}")

======================================================================
BEST FEATURE PER GROUP PER TARGET
======================================================================

──────────────────────────────────────────────────────────────────────
GROUP: fiber
Rationale: per_1000kcal normalizes for total intake
──────────────────────────────────────────────────────────────────────
Target                    Winner                        Corr Runner-up                     Corr
-----------------------------------------------------------------------------------------------
  triglycerides           fiber                      -0.0377 fiber_per_1000kcal         -0.0358 ≈
  hba1c                   fiber                      -0.0540 fiber_per_1000kcal         -0.0207
  vitamin_d               fiber_per_1000kcal          0.1236 fiber                       0.0745
  alt                     fiber                       0.0651 fiber_per_1000kcal         -0.0539 ≈
  albumin                 fiber                       0.1168 fiber_per_1000kcal          0.0693
  alp                     fiber                      -0.1120 fiber_per_1000kcal         -0.1005 ≈
  ast                     fiber                       0.0808 fiber_per_1000kcal         -0.0086
  bun                     fiber                       0.0865 fiber_per_1000kcal          0.0485
  hdl_cholesterol         fiber_per_1000kcal          0.1095 fiber                       0.0322
  ldl_cholesterol         fiber_per_1000kcal          0.0359 fiber                       0.0138
  cholesterol_total       fiber_per_1000kcal          0.0368 fiber                       0.0174 ≈
  hscrp                   fiber                      -0.1389 fiber_per_1000kcal         -0.1169

  → Wins across targets: fiber: 8, fiber_per_1000kcal: 4
  → Recommended to KEEP: fiber

──────────────────────────────────────────────────────────────────────
GROUP: fat_total
Rationale: pct normalizes for total intake
──────────────────────────────────────────────────────────────────────
Target                    Winner                        Corr Runner-up                     Corr
-----------------------------------------------------------------------------------------------
  triglycerides           fat_pct                    -0.0321 fat                        -0.0057
  hba1c                   fat_pct                     0.0518 fat                        -0.0164
  vitamin_d               fat_pct                     0.0745 fat                        -0.0045
  alt                     fat                         0.1138 fat_pct                    -0.0412
  albumin                 fat                         0.0708 fat_pct                    -0.0073
  alp                     fat                        -0.0575 fat_pct                    -0.0521 ≈
  ast                     fat                         0.0729 fat_pct                    -0.0610 ≈
  bun                     fat                         0.1009 fat_pct                     0.0779
  hdl_cholesterol         fat                        -0.0728 fat_pct                     0.0191
  ldl_cholesterol         fat                        -0.0171 fat_pct                     0.0032 ≈
  cholesterol_total       fat                        -0.0182 fat_pct                    -0.0022 ≈
  hscrp                   fat                        -0.0347 fat_pct                     0.0165 ≈

  → Wins across targets: fat: 9, fat_pct: 3
  → Recommended to KEEP: fat

──────────────────────────────────────────────────────────────────────
GROUP: carbs
Rationale: pct normalizes for total intake
──────────────────────────────────────────────────────────────────────
Target                    Winner                        Corr Runner-up                     Corr
-----------------------------------------------------------------------------------------------
  triglycerides           carbs_pct                   0.0646 carbs                       0.0303
  hba1c                   carbs                      -0.0456 carbs_pct                  -0.0023
  vitamin_d               carbs                      -0.0709 carbs_pct                  -0.0664 ≈
  alt                     carbs                       0.1098 carbs_pct                  -0.0596
  albumin                 carbs                       0.0493 carbs_pct                  -0.0483 ≈
  alp                     carbs_pct                   0.0811 carbs                       0.0041
  ast                     carbs                       0.0872 carbs_pct                  -0.0474
  bun                     carbs_pct                  -0.1248 carbs                      -0.0018
  hdl_cholesterol         carbs                      -0.1310 carbs_pct                  -0.0920
  ldl_cholesterol         carbs_pct                  -0.0218 carbs                      -0.0211 ≈
  cholesterol_total       carbs_pct                  -0.0421 carbs                      -0.0341 ≈
  hscrp                   carbs                      -0.0475 carbs_pct                   0.0045

  → Wins across targets: carbs: 7, carbs_pct: 5
  → Recommended to KEEP: carbs

──────────────────────────────────────────────────────────────────────
GROUP: protein
Rationale: pct normalizes for total intake
──────────────────────────────────────────────────────────────────────
Target                    Winner                        Corr Runner-up                     Corr
-----------------------------------------------------------------------------------------------
  triglycerides           protein                    -0.0276 protein_pct                -0.0272 ≈
  hba1c                   protein                    -0.0371 protein_pct                 0.0249 ≈
  vitamin_d               protein_pct                 0.0327 protein                    -0.0213 ≈
  alt                     protein                     0.1767 protein_pct                 0.0545
  albumin                 protein                     0.1216 protein_pct                 0.0604
  alp                     protein                    -0.0682 protein_pct                -0.0455
  ast                     protein                     0.1211 protein_pct                 0.0132
  bun                     protein                     0.1631 protein_pct                 0.1623 ≈
  hdl_cholesterol         protein                    -0.0877 protein_pct                -0.0203
  ldl_cholesterol         protein                    -0.0133 protein_pct                 0.0047 ≈
  cholesterol_total       protein                    -0.0235 protein_pct                -0.0181 ≈
  hscrp                   protein                    -0.0612 protein_pct                -0.0123

  → Wins across targets: protein: 11, protein_pct: 1
  → Recommended to KEEP: protein

──────────────────────────────────────────────────────────────────────
GROUP: blood_pressure
Rationale: map is linear combination of bp_sys and bp_di
──────────────────────────────────────────────────────────────────────
Target                    Winner                        Corr Runner-up                     Corr
-----------------------------------------------------------------------------------------------
  triglycerides           map                         0.2080 bp_di                       0.1966 ≈
  hba1c                   bp_sys                      0.2415 map                         0.1809
  vitamin_d               bp_di                      -0.0805 bp_sys                      0.0530
  alt                     map                         0.1810 bp_sys                      0.1675 ≈
  albumin                 map                        -0.0278 bp_di                      -0.0275 ≈
  alp                     bp_sys                      0.1445 map                         0.1357 ≈
  ast                     bp_sys                      0.1839 map                         0.1362
  bun                     bp_sys                      0.1294 bp_di                      -0.0678
  hdl_cholesterol         bp_di                      -0.0473 map                        -0.0265
  ldl_cholesterol         bp_di                       0.1786 map                         0.1164
  cholesterol_total       bp_di                       0.2018 map                         0.1646
  hscrp                   bp_di                       0.1732 map                         0.1394

  → Wins across targets: bp_di: 5, bp_sys: 4, map: 3
  → Recommended to KEEP: bp_di

──────────────────────────────────────────────────────────────────────
GROUP: physical_activity
Rationale: mets combines mod and vig; sedentary is independent
──────────────────────────────────────────────────────────────────────
Target                    Winner                        Corr Runner-up                     Corr
-----------------------------------------------------------------------------------------------
  triglycerides           mod_pa_min_per_wk          -0.0739 total_pa_mets_per_wk       -0.0670 ≈
  hba1c                   meets_pa_guidelines        -0.0770 sedentary_time_per_day     -0.0655 ≈
  vitamin_d               meets_pa_guidelines         0.0267 sedentary_time_per_day     -0.0225 ≈
  alt                     vig_pa_min_per_wk           0.0406 total_pa_mets_per_wk        0.0288 ≈
  albumin                 mod_pa_min_per_wk           0.0773 meets_pa_guidelines         0.0548
  alp                     mod_pa_min_per_wk          -0.0384 meets_pa_guidelines        -0.0335 ≈
  ast                     vig_pa_min_per_wk           0.0927 total_pa_mets_per_wk        0.0884 ≈
  bun                     total_pa_mets_per_wk        0.0410 sedentary_time_per_day     -0.0342 ≈
  hdl_cholesterol         sedentary_time_per_day     -0.0474 meets_pa_guidelines         0.0197
  ldl_cholesterol         vig_pa_min_per_wk          -0.0668 total_pa_mets_per_wk       -0.0584 ≈
  cholesterol_total       total_pa_mets_per_wk       -0.0605 vig_pa_min_per_wk          -0.0503 ≈
  hscrp                   meets_pa_guidelines        -0.0644 total_pa_mets_per_wk       -0.0538 ≈

  → Wins across targets: mod_pa_min_per_wk: 3, vig_pa_min_per_wk: 3, meets_pa_guidelines: 3, total_pa_mets_per_wk: 2, sedentary_time_per_day: 1
  → Recommended to KEEP: mod_pa_min_per_wk

──────────────────────────────────────────────────────────────────────
GROUP: fat_subtypes
Rationale: subtypes may add independent signal beyond total pct
──────────────────────────────────────────────────────────────────────
Target                    Winner                        Corr Runner-up                     Corr
-----------------------------------------------------------------------------------------------
  triglycerides           fat_pct                    -0.0321 mono_fat                   -0.0202 ≈
  hba1c                   fat_pct                     0.0518 poly_fat                   -0.0326 ≈
  vitamin_d               fat_pct                     0.0745 mono_fat                   -0.0119
  alt                     mono_fat                    0.1088 sat_fat                     0.1066 ≈
  albumin                 mono_fat                    0.0762 poly_fat                    0.0629 ≈
  alp                     poly_fat                   -0.0707 mono_fat                   -0.0628 ≈
  ast                     mono_fat                    0.0728 poly_fat                    0.0630 ≈
  bun                     sat_fat                     0.1074 mono_fat                    0.0966 ≈
  hdl_cholesterol         sat_fat                    -0.0731 mono_fat                   -0.0649 ≈
  ldl_cholesterol         sat_fat                    -0.0246 mono_fat                   -0.0180 ≈
  cholesterol_total       sat_fat                    -0.0238 mono_fat                   -0.0218 ≈
  hscrp                   poly_fat                   -0.0538 mono_fat                   -0.0475 ≈

  → Wins across targets: sat_fat: 4, mono_fat: 3, fat_pct: 3, poly_fat: 2
  → Recommended to KEEP: sat_fat

──────────────────────────────────────────────────────────────────────
GROUP: calories
Rationale: pct features absorb kcal information
──────────────────────────────────────────────────────────────────────
Target                    Winner                        Corr Runner-up                     Corr
-----------------------------------------------------------------------------------------------
  triglycerides           carbs_pct                   0.0646 fat_pct                    -0.0321
  hba1c                   fat_pct                     0.0518 kcal                       -0.0502 ≈
  vitamin_d               fat_pct                     0.0745 carbs_pct                  -0.0664 ≈
  alt                     kcal                        0.1621 carbs_pct                  -0.0596
  albumin                 kcal                        0.0868 protein_pct                 0.0604
  alp                     carbs_pct                   0.0811 fat_pct                    -0.0521
  ast                     kcal                        0.1286 fat_pct                    -0.0610
  bun                     protein_pct                 0.1623 carbs_pct                  -0.1248
  hdl_cholesterol         kcal                       -0.1020 carbs_pct                  -0.0920 ≈
  ldl_cholesterol         carbs_pct                  -0.0218 kcal                       -0.0169 ≈
  cholesterol_total       carbs_pct                  -0.0421 kcal                       -0.0184
  hscrp                   kcal                       -0.0554 fat_pct                     0.0165

  → Wins across targets: kcal: 5, carbs_pct: 4, fat_pct: 2, protein_pct: 1
  → Recommended to KEEP: kcal

======================================================================
FINAL RECOMMENDATIONS
======================================================================
  KEEP: fiber                          (winner in fiber, 42.8% missing)
  KEEP: fat                            (winner in fat_total, 42.8% missing)
  KEEP: carbs                          (winner in carbs, 42.8% missing)
  KEEP: protein                        (winner in protein, 42.8% missing)
  KEEP: bp_di                          (winner in blood_pressure, 24.0% missing)
  KEEP: mod_pa_min_per_wk              (winner in physical_activity, 20.7% missing)
  KEEP: sat_fat                        (winner in fat_subtypes, 42.8% missing)
  KEEP: kcal                           (winner in calories, 42.8% missing)

Features to KEEP (8): ['bp_di', 'carbs', 'fat', 'fiber', 'kcal', 'mod_pa_min_per_wk', 'protein', 'sat_fat']
Features to DROP (12): ['bp_sys', 'carbs_pct', 'fat_pct', 'fiber_per_1000kcal', 'map', 'meets_pa_guidelines', 'mono_fat', 'poly_fat', 'protein_pct', 'sedentary_time_per_day', 'total_pa_mets_per_wk', 'vig_pa_min_per_wk']

======================================================================
UPDATED DROP_COLS ADDITION
======================================================================

Add these to your DROP_COLS list:
REDUNDANT_FEATURES = ['bp_sys', 'carbs_pct', 'fat_pct', 'fiber_per_1000kcal', 'map', 'meets_pa_guidelines', 'mono_fat', 'poly_fat', 'protein_pct', 'sedentary_time_per_day', 'total_pa_mets_per_wk', 'vig_pa_min_per_wk']

In [110]:
REDUNDANT_FEATURES = [
    "mod_pa_min_per_wk",
    "vig_pa_min_per_wk",
    "meets_pa_guidelines",
    "fiber_per_1000kcal",
    "protein_pct",
    "fat_pct",
    "carbs_pct",
    "bp_sys",
    "bp_di"]

In [111]:
df_copy.drop(columns = REDUNDANT_FEATURES, inplace=True)

In [112]:
df_copy.to_csv('nhanes_all_processed.csv', index=False)